### ISSUE TITLE
bug: Security Insights: no GitHub.com slug results in error page

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/roadie-backstage-plugins#1008]
## Expected Behavior

Errors are cleanly trapped.

## Current Behavior

I happened to have a static entity which was being opened by a local YAML reference, and it did not have a GitHub slug.
I turned off the "isSecurityInsightsEnabled" and added the Dependabot card to a grid layout.

When loading this entity, my front end crashes with a large error page.

<img width="1118" alt="image" src="https://github.com/RoadieHQ/roadie-backstage-plugins/assets/33203301/5a7685a0-1958-4ce7-8d2e-aacb1d78f0c9">

## Steps to Reproduce

1. Add a local entity reference via a location w/o a GitHub.com project slug (e.g., no `github.com/project-slug: <org>/<repo>`
2. Use a Dependabot card from the Security Insights plugin in a grid layout, and to not have that route or grid protected by the `isSecurityInsightsEnabled`

## Possible Solution

Obviously, if the isSecurityInsightsEnabled was false this wouldn't have landed. But in such cases where I'd like the card widget in a way to warn the user it lacks a GitHub reference, it would be great to trap this and print a more friendly card return to the user saying something like annotation missing or something to that effect to guide the user to add it.  obviously, if it was dynamically generated backstage would have added this annotation for me, but since it was local it did not reflect. (and can imagine other scenarios where users might stitch components and have this card on a grid w/o the annotation)

So it should just be trapped IMHO.

## Your Environment

- `@backstage/plugin-catalog-react` version:
- `@backstage/integration` version:

**Comment by adamdmharvey** [comment]
PS: I did find more more thing. It does not use the inherited ones as I have a catalog YAML that also does not have a GitHub.com slug, but with these autogenerated annotations: 
<img width="511" alt="image" src="https://github.com/RoadieHQ/roadie-backstage-plugins/assets/33203301/0e6b464f-23b9-4362-a563-2348ccb82fde">

I would THINK in such instances we could infer it has GitHub even w/o the slug? but happy to learn best practice from Roadie or other's experience here. I'd hate to ask all of my users when they put catalog info YAMLs into GitHub, the they need to also explicitly SAY they have GitHub - feel like that should be inferred.

**Comment by kissmikijr** [comment]
>I would THINK in such instances we could infer it has GitHub even w/o the slug? but happy to learn best practice from Roadie or other's experience here. I'd hate to ask all of my users when they put catalog info YAMLs into GitHub, the they need to also explicitly SAY they have GitHub - feel like that should be inferred.

I mean kinda the whole philosophy of Backstage is to manually curate your entity files by each team on its own. It is not really designed to figure these out. Furthermore we could know that this entity is coming from github, but we don't know the github project. There is no guarantee you put your yaml files in the repo that they are referencing.

**Comment by adamdmharvey** [comment]
Right, that's a great point @kissmikijr ! (and indeed, we have a few "holder" repos where teams are experimenting with curating a few entities in the single place, so good call out)
