### ISSUE TITLE
hierarchyConfig doesn't work

### ISSUE THREAD

**Issue by swood** [RoadieHQ/roadie-backstage-plugins#1009]
When I add the hierarchyConfig section, the Backstage doesn't import any group.

## Expected Behavior

I expect that hierarchyConfig would import a parent group from Okta according to the group attribute.

## Current Behavior

A parent group doesn't appear in Backstage.

## Steps to Reproduce

I configured the plugin according to the plugin documentation. I added the orgId and parentOrgId to the group profile in Okta.
However, as soon as I added the hierarchyConfig, the plugin stopped importing any groups from Okta. 
The filter in the app-config.yaml is below:
> groupFilter: profile.orgId eq "Parent_Group"

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.7.0-next.1
- `@backstage/integration` version: 1.5.0-next.0

**Comment by swood** [comment]
Sorry, I don't have access to this ticket.

**Comment by kissmikijr** [comment]
Ah yea, don't worry about it, it's for our internal system where we track these issues! :)

**Comment by swood** [comment]
Hi, any chance for any answer?
