### ISSUE TITLE
Aws-Lambda-Plugin

### ISSUE THREAD

**Issue by ValberJunior** [RoadieHQ/roadie-backstage-plugins#1016]
![print2](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/84424883/59e8b693-562e-4bbb-b80a-6affa59a6683)

![print1](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/84424883/57c8474e-fa20-4e9c-b4c0-9c4030cc0acd)

According to the documentation, to add more than one function, just separate them with a comma, but when doing so, this error appears:

https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-aws-lambda

>1 validation error detected: Value 'teste-lambda-start,teste-lambda-stop' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-.]+)(:($LATEST|[a-zA-Z0-9-]+))?

Taking a look at the core of the plugin, it expects a string in this annotation:

```js
"properties" : {
    "aws.com/lambda-function-name": {"type":"string"}
    }
 ```

Could you help me on this issue? I need to make 2 functions available in the component's overview and I'm not getting it for that reason.

OBS:
version: "@roadiehq/backstage-plugin-aws-lambda": "^2.1.9",

**Comment by Xantier** [comment]
Thanks, it looks like that functionality is not something supported by the plugin at the moment. If you want to implement the modifications to support this, we are more than happy to review the pull request. I opened a PR to update the README here: https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1029

**Comment by ValberJunior** [comment]
https://github.com/RoadieHQ/roadie-backstage-plugins/compare/main...ValberJunior:roadie-backstage-plugins:patch-1
https://github.com/RoadieHQ/roadie-backstage-plugins/compare/main...ValberJunior:roadie-backstage-plugins:patch-2

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/84424883/ea7c17ec-377c-495f-9042-4e6cfb0ea5ff)
