### ISSUE TITLE
[backstage-plugin-argo-cd-backend] Support apps in any namespace

### ISSUE THREAD

**Issue by mwienk** [RoadieHQ/roadie-backstage-plugins#1038]
## Feature Suggestion

As Argo CD supports having applications in multiple namespaces, I think the backstage plugin should support that too.

## Possible Implementation

The component should have an argocd namespace annotation, e.g. `argocd/app-namespace: <app-namespace>` which should be used in the backend API calls as the appNamespace parameter.

In order to support the app-selector, the namespace should be extracted from the application after the first request and used in subsequent requests that use the name in the url.

## Context

Although still beta, Argo CD supports defining applications in any namespace (https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/). Currently those applications cannot properly be shown in backstage. Targeting them with labels still doesn't work, as the calls for revision metadatas are using the application name.

**Comment by kissmikijr** [comment]
As you mentioned above this Argo CD feature is in Beta. I'd rather not jump on this immediately and would wait for a stable release.

**Comment by dubuc** [comment]
https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1068

Closing above in favour of this one.
