### ISSUE TITLE
Add examples for all scaffolder actions

### ISSUE THREAD

**Issue by punkle** [RoadieHQ/roadie-backstage-plugins#1071]
Each scaffolder action can be supplied with examples. These examples appear in the installed actions page in the backstage ui.

## Feature Suggestion
It would be great for these examples to be complete to make it easier for writers of templates.

## Possible Implementation

If you look at this pull request in the backstage repo, you can see how examples can be added to the actions provided in this repo:

https://github.com/backstage/backstage/pull/18831

## Context

By adding these examples, it allows the template writer a reference for what can be done with a template. 

- [ ] roadiehq:utils:jsonata
- [ ] argocd:create-resources
- [ ] roadiehq:aws:ecr:create
- [ ] argocd:create-resources
- [ ] roadiehq:aws:s3:cp
- [ ] roadiehq:aws:secrets-manager:create
- [ ] http:backstage:request
- [ ] roadiehq:utils:fs:append
- [ ] roadiehq:utils:fs:parse
- [ ] roadiehq:utils:fs:replace
- [ ] roadiehq:utils:fs:write
- [ ] roadiehq:utils:jsonata:json:transform
- [ ] roadiehq:utils:sleep
- [ ] roadiehq:utils:zip
- [ ] roadiehq:utils:serialize:yaml
- [ ] roadiehq:utils:serialize:json
- [ ] roadiehq:utils:merge
- [ ] roadiehq:utils:json:merge
- [ ] roadiehq:utils:jsonata:yaml:transform
- [ ] roadiehq:utils:jsonata

**Comment by Stroller15** [comment]
Hi, @punkle Can you please assign this issue to me? I can help out with this

**Comment by Xantier** [comment]
Thanks @Stroller15 ! 

Assigned.

**Comment by punkle** [comment]
@Stroller15, of course. Done. Let me know if I can help in any way.

**Comment by Stroller15** [comment]
@punkle

Is there any communication channel I can join for communication?

**Comment by punkle** [comment]
@Stroller15 we have a public discord server. https://discord.com/invite/DUS3u7sP

**Comment by Stroller15** [comment]
> @Stroller15 we have a public discord server. https://discord.com/invite/DUS3u7sP

Thank you @punkle , I will contact there if I encounter any difficulties in the project.

**Comment by punkle** [comment]
Thanks @Stroller15

**Comment by Stroller15** [comment]
hey @punkle I tried many time but not able to setup locally this project, can you help me with this or any suggestion

**Comment by punkle** [comment]
@Stroller15 what challenge are you running into?

**Comment by punkle** [comment]
Not stale
