### ISSUE TITLE
[backstage-plugin-github-pull-requests] Base-URL for Repository is statically taken from integrations Config

### ISSUE THREAD

**Issue by enyineer** [RoadieHQ/roadie-backstage-plugins#1083]
Hello,

I do have a problem with the Base-URL being statically taken from the integrations-Config (first element of array) in the PR-Plugin for Backstage while having multiple GHE-Instances that are part of the GitHub Catalog Discovery.

See [this code](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/52533e3e1193b82715a5f216cccb00d0ff7aace7/plugins/frontend/backstage-plugin-github-pull-requests/src/components/useBaseUrl.ts#L23) for reference of what causes this.

I've been thinking about multiple possible fixes. We could use eg. `backstage.io/source-location` to derive the hostname from and then searching inside of the `integrations.github` Config array to look for a matching "host". If none is found, it could default to the current behaviour.

Any thoughts about that?

**Comment by enyineer** [comment]
One more problem that might arise from this is that we can only define a single OAuth app under `auth.providers.github` which might probably lead to wrong OAuth tokens being requested (from the wrong GHE instance) if the project originates from another instance.

**Comment by kissmikijr** [comment]
Thank you, yes this currently only supports one github entry in the app-config.yaml
