### ISSUE TITLE
Create the issues view for the jira plugin 

### ISSUE THREAD

**Issue by riginoommen** [RoadieHQ/roadie-backstage-plugins#1084]

**Comment by riginoommen** [comment]
![Screenshot 2023-09-11 at 12 51 28 PM](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/3840244/5c208cab-50ae-42a3-9212-fbe59ce65bd9)

I extended this plugin like this

**Comment by winterji** [comment]
Hey @riginoommen, that looks useful. Could you please share how you achieved that?

**Comment by riginoommen** [comment]
I took this code and extended this. i will open a pull request to this repo soon

**Comment by riginoommen** [comment]
I have created the pull request along with this feature
