### ISSUE TITLE
Importing `createCardExtension` from `@backstage/plugin-home-react`

### ISSUE THREAD

**Issue by freben** [RoadieHQ/roadie-backstage-plugins#1114]
Hi friends!

## Feature Suggestion

Several of the plugins in this repo implement support for Home plugin cards. They have a dependency on `@backstage/plugin-home` to get access to `createCardExtension`. That export is deprecated, and should now instead be taken from `@backstage/plugin-home-react`.

## Context

When reviewing https://github.com/backstage/backstage/pull/19827 I noticed that the old version of `rjsf` weas kept around in the lockfile because of some third party dependencies on older versions of the `home` plugin. And I'm on a bit of an overall mission to get rid of plugins-depending-on-plugins, which should be avoided. So remember to remove the old `package.json` deps!

**Comment by awanlin** [comment]
I've submitted a PR #1140 to resolve this as it's impacted our ability to upgrade to the latest version of Backstage
