### ISSUE TITLE
Links and images in the Readme card are displayed as broken

### ISSUE THREAD

**Issue by renatafaracobah** [RoadieHQ/roadie-backstage-plugins#1118]
## Expected Behavior

* Relative links should be rendered as `https://<github-url>/<org>/<repo>/blob/develop/<relative-link>`
* Images should be rendered, even if the URL is relative (example: `src=“image/cover.png”`)
* External links should be opened in a new tab

## Current Behavior

* Relative links always use github.com instead of finding the appropriate host based on the repository's location, which could be an enterprise GitHub Enterprise host. 
* Images with relative path show as broken (it renders as `<current-page>/image/cover.png` and not  `https://<github-url>/<org>/<repo>/blob/develop/image/cover.png`)
* Internal links are opened in the current tab

## Steps to Reproduce

1. Add those examples to the Readme.md file of a repository and make sure the page/image exists in the repository
```
Click [here](/docs/somepage.md)

![Image](/docs/cover.png)

[External link](https://designsystem.digital.gov/)
```
2. Go to the entity page with the Roadies plugin card of the specific repository entity. 
3. Check for the image: it’ll be rendered as broken.
4. Click on the `Click here` link: it’ll send the user to a broken page.
5. Click on the `External link` link: it should be opened in a new tab, but it does not.
![relative-link2](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/93277286/a99ec583-2071-40b3-a927-f59b08265007)

## Context

We are using the GH Insights Roadie plugin to display the Readme file for several entities (components, systems, domains, templates) to encourage our users to go to the docs and find more information. 

## Your Environment

* `@backstage/plugin-catalog-react` version: ^1.8.3
* `@backstage/integration` version: ^1.6.2
* `@roadiehq/backstage-plugin-github-insights` version: ^2.3.20

**Comment by ltdonner-bah** [comment]
unstale, please

**Comment by ltdonner-bah** [comment]
unstale please

**Comment by ltdonner-bah** [comment]
unstale please

**Comment by thiago-scherrer** [comment]
Same problem here: 

`@backstage/plugin-catalog-react` ^1.10.0
`@backstage/integration` ^1.9.0
`@roadiehq/backstage-plugin-github-insights` ^2.3.23

**Comment by renatafaracobah** [comment]
unstale please & ty
