### ISSUE TITLE
ArgoCD plugin - Exhaustion of upstream ArgoCD instance while querying for revisions

### ISSUE THREAD

**Issue by Rbillon59** [RoadieHQ/roadie-backstage-plugins#1121]
From the issue : https://github.com/RoadieHQ/roadie-backstage-plugins/issues/881
And the PR : https://github.com/RoadieHQ/roadie-backstage-plugins/pull/907

1. The revisions feature adds more information to the ArgoCD plugin to be able to show revision history. Doing so, the plugin will request the metadata to the upstream argocd instance. But in our case with a lot of resources and history, *it could take up to 700 requests in parallel for a single entity to load.

Those important number of parallel requests are impacting the upstream Argocd Instance and finally ends up on 504 because the requests are taking more than 30s.

2. Even if not using the [ArgoCDHistoryCard](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDHistoryCard.tsx), the revisions calls are triggered.

3. The whole Component is showing a 504 if at least 1 of those request is failing, even if the 699 other don't

## Expected Behavior

If not using the ArgoCDHistoryCard, the revisions should not be called
The feature should not exhaust upstream argocd instance

## Current Behavior

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/17565349/65c9cc1e-93da-4b16-ab54-7287bab6b513)

The data queried during that loading were only used by the [ArgoCDHistoryCard](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDHistoryCard.tsx) component.

But even if you're not using that card, those calls are made because the [EntityArgoCDOverviewCard](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/c318f170de90cd063265d63a50fe9baada031fbe/plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDDetailsCard.tsx) is calling the [useAppDetails](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/c318f170de90cd063265d63a50fe9baada031fbe/plugins/frontend/backstage-plugin-argo-cd/src/components/useAppDetails.ts)

## Steps to Reproduce

- Having an upstream ArgoCD instance having an application deployed in few clusters
- Having a ArgoCD source repository with a consequent history

## Possible Solution

- Render the component in a lazy loading fashion (not waiting for all requests to be finished to render) + limiting the number of concurrent requests.

- Batch the requests to make one request to the argocd API with the needed revisions (the sum of data for the 700+ requests is ~2,5MB) **(No endpoint available in ArgoCD yet)**

- Have a configurable limit on the number of revisions to get

- As revisions do not really tend to change over time, caching them would be efficient

## Your Environment

   "@backstage/app-defaults": "^1.4.0",
    "@backstage/catalog-model": "^1.4.0",
    "@backstage/cli": "^0.22.8",
    "@backstage/core-app-api": "^1.8.1",
    "@backstage/core-components": "^0.13.2",
    "@backstage/core-plugin-api": "^1.5.2",
    "@backstage/integration-react": "^1.1.14",
    "@backstage/plugin-adr": "^0.6.2",
    "@backstage/plugin-adr-common": "^0.2.10",
    "@backstage/plugin-api-docs": "^0.9.5",
    "@backstage/plugin-badges": "^0.2.43",
    "@backstage/plugin-catalog": "^1.11.2",
    "@backstage/plugin-catalog-common": "^1.0.14",
    "@backstage/plugin-catalog-graph": "^0.2.31",
    "@backstage/plugin-catalog-import": "^0.9.9",
    "@backstage/plugin-catalog-react": "^1.7.0",
    "@backstage/plugin-github-actions": "^0.6.0",
    "@backstage/plugin-github-pull-requests-board": "^0.1.13",
    "@backstage/plugin-home": "^0.5.3",
    "@backstage/plugin-org": "^0.6.9",
    "@backstage/plugin-permission-common": "^0.7.6",
    "@backstage/plugin-permission-react": "^0.4.13",
    "@backstage/plugin-playlist": "^0.1.11",
    "@backstage/plugin-scaffolder": "^1.14.0",
    "@backstage/plugin-scaffolder-common": "^1.3.1",
    "@backstage/plugin-search": "^1.3.2",
    "@backstage/plugin-search-react": "^1.6.2",
    "@backstage/plugin-shortcuts": "^0.3.11",
    "@backstage/plugin-sonarqube": "^0.7.0",
    "@backstage/plugin-tech-insights": "^0.3.11",
    "@backstage/plugin-tech-insights-common": "^0.2.11",
    "@backstage/plugin-tech-radar": "^0.6.5",
    "@backstage/plugin-techdocs": "^1.6.4",
    "@backstage/plugin-techdocs-module-addons-contrib": "^1.0.14",
    "@backstage/plugin-techdocs-react": "^1.1.7",
    "@backstage/plugin-user-settings": "^0.7.4",
    "@backstage/theme": "^0.4.0",
    "@datadog/browser-rum": "^4.42.2",
    "@drodil/backstage-plugin-toolbox": "^1.9.2",
    "@material-ui/core": "^4.12.2",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.61",
    "@roadiehq/backstage-plugin-argo-cd": "2.2.10",
    "@roadiehq/backstage-plugin-github-insights": "^2.3.15",
    "@roadiehq/backstage-plugin-github-pull-requests": "^2.5.13",
    "@iconify/react": "^4.1.0",
    "history": "^5.3.0",
    "lodash": "^4.17.21",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router": "6.11.1",
    "react-router-dom": "6.11.1",
    "react-use": "^17.4.0",
    "classnames": "2.3.2"

**Comment by k7k0** [comment]
+1 also `getRevisionData` is now very resilience, if one of those revisions in the history is not available, for example branch was removed,  the whole request will fail with an exception

**Comment by KatharinaSick** [comment]
Hi,

I'll look into this and try to provide a fix :slightly_smiling_face:

**Comment by Rbillon59** [comment]
> Hi,
> 
> I'll look into this and try to provide a fix :slightly_smiling_face: 

Thanks you! Happy to participate in the review process

**Comment by Rbillon59** [comment]
> Hi,
> 
> I'll look into this and try to provide a fix :slightly_smiling_face: 

Hey,

I was thinking of making the revision history calls toogable if it makes sense

**Comment by KatharinaSick** [comment]
Hmm but don't you always want to have the revision history in the `HistoryCard`? I'm now working on an approach to lazy load all revisions and maybe limit the number of revisions in the config as you stated above. But maybe toggling would make sense as well? 

Btw, I'm sorry that it takes so long. We had an urgent bug to fix and now I'm ill. But I think I can create a PR tomorrow :)

**Comment by Rbillon59** [comment]
Yes for the history card it's normal to have it, I was thinking about that part I wrote in the issue : 

> But even if you're not using that card, those calls are made because the [EntityArgoCDOverviewCard](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/c318f170de90cd063265d63a50fe9baada031fbe/plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDDetailsCard.tsx) is calling the [useAppDetails](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/c318f170de90cd063265d63a50fe9baada031fbe/plugins/frontend/backstage-plugin-argo-cd/src/components/useAppDetails.ts)

Having a good separation of concern on the `EntityArgoCDOverviewCard`. Like not calling the revision history on a component not using that data

**Comment by KatharinaSick** [comment]
Oh yes - I already completely removed the revisions call from the overview card and created a `useAppRevisions` function to load the revisions :)

**Comment by Rbillon59** [comment]
Fixed by #1197
