### ISSUE TITLE
[scaffolder-backend-module-utils] add indention options in roadiehq:utils:fs:append action content

### ISSUE THREAD

**Issue by ronballesteros** [RoadieHQ/roadie-backstage-plugins#1133]
Hello, would love to see similar options for the `roadiehq:utils:fs:append` backstage action like we do in other roadie utils.

For example, with this given file (see below), would like to append the file with an indention.  Right now the append util will append the file but leave it un-indented (like the below file).

```
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ns.yaml
  - backstage.yaml
  - app1.yaml
  - app2.yaml
 ```

```
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ns.yaml
  - backstage.yaml
  - app1.yaml
  - app2.yaml
- app3.yaml
 ```

## Feature Suggestion

This would allow us to have the Github Workflow pass and not complain about the file formatting.

**Comment by brunosantosnet** [comment]
+1

**Comment by ronballesteros** [comment]
@brunosantosnet - I was able to get around this by using a combination of utils like so (see below).

Basically:
1. fetch the directory using fetch:plain
2. use the roadiehq:utils:jsonata:yaml:transform along with a jsonata expression to update the file
3. write the file

More steps involved, but it works for me.

`

    - id: fetch-repo
      name: Live - Argo Deploy Repo Template
      action: fetch:plain
      input:
        url: ./deploy/${{ parameters.project_team }}
        targetPath: ./argocd-repo
    
    - id: transform-argo-kustomization-file
      name: Live - Update Argo Kustomization File
      action: roadiehq:utils:jsonata:yaml:transform
      input:
        path: ./argocd-repo/kustomization.yaml
        expression: '$ ~> | $ | { "resources": [resources, "${{ parameters.app_name }}-applicationset.yaml"] }|'

    - id: write-argo-kustomization-file
      name: Live - Write Argo Kustomization File
      action: roadiehq:utils:fs:write
      input:
        path: ./argocd-repo/kustomization.yaml
        content: ${{ steps['transform-argo-kustomization-file'].output.result }}
`
