### ISSUE TITLE
roadiehq:utils:merge to support appending to existing array

### ISSUE THREAD

**Issue by kissmikijr** [RoadieHQ/roadie-backstage-plugins#1172]
The current implementation of the roadiehq:utils:merge action uses the merge function from lodash. This has a limitation where it cannot extend array values when you want to merge. When they keys are the same the new value will replace the old one.
## Feature Suggestion
Make merge to be able to extend existing array values by the provided additions.

## Possible Implementation
Could be to implement the whole merge on our own instead of using lodash. 

We could implement only our own merge in the case of array values and do the merge in 2 steps with checking if there is any array value in the incoming change.

## Context
One of the use case is to add new values to a Location entities' targets array via this action

**Comment by iain-b** [comment]
This was fixed in #1201
