### ISSUE TITLE
Using Pull requests plugin without adding Github Auth 

### ISSUE THREAD

**Issue by Pvv7707** [RoadieHQ/roadie-backstage-plugins#1176]
Is there a way to implement this github pull request plugin without having auth setup of github as we have OIDC setup currently 
## Feature Suggestion

If there is any mocking approach for achieving this without actual github setup

**Comment by matarnold-dev** [comment]
I too have a similar issue.  It looks like the github pull requests plugin requires a Backstage user to login to Backstage with their github login for the plugin to work.  Is that right?  If so, I'd like to also request the github pull requests plugin to work only using the client id and secret.
