### ISSUE TITLE
ArgoCD app selector appears to be broken in latest version

### ISSUE THREAD

**Issue by dwilliams782** [RoadieHQ/roadie-backstage-plugins#1181]
With the latest ArgoCD plugin (2.4.0), when specifying `argocd/app-selector` annotation, this is ignored and will show all applications after querying every revision even when just using the Overview card (I see a bug for this already: https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1121) . 

I downgraded the plugin to 2.2.10 and it works normally. EDIT: Also tried latest-1, 2.3.6, which is good as well.

## Expected Behavior

With a component like:

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    argocd/app-selector: "app=sysops-db-tools"
```

The filter should be passed to the argocd proxy i.e.

```
[1] 2023-11-16T13:08:51.841Z backstage info ::1 - - [16/Nov/2023:13:08:51 +0000] "GET /api/proxy/argocd/api/applications?selector=app%3Dsysops-db-tools HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" type=incomingRequest
```

Above log taken from working 2.2.10 plugin.

## Current Behavior

The selector is ignored and we see all applications in the ArgoCD Overview.

```
[1] 2023-11-16T13:16:31.145Z backstage info ::1 - - [16/Nov/2023:13:16:31 +0000] "GET /api/proxy/argocd/api/applications HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" type=incomingRequest

```

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/42545485/18144b7e-e77c-4ace-923a-772abbd7f304)

Above logs taken with 2.4.0 installed.

## Steps to Reproduce

Install ArgoCD plugin 2.4.0 using the instructions found [here](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-argo-cd).

## Your Environment

- `@backstage/plugin-catalog-react` version: ^1.8.5
- `@backstage/integration` version: ^1.7.1

**Comment by dwilliams782** [comment]
With version 2.3.6, the filter is applied but we also get all the revisions even though I'm only using the Overview card:

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/42545485/1d7c4a85-1411-4d76-81aa-e06a3f164bcb)

So this issue comes in only with 2.4.0.

**Comment by alecjacobs5401** [comment]
+1 - when using an ArgoCD that managed hundreds of deployed apps, this completely breaks the plugin usage and locks up the page.

Im fairly certain [this change](https://github.com/TRIMM/roadie-backstage-plugins/blob/9ff37295de1f64c30d00d11a37c1ca569620b53d/plugins/frontend/backstage-plugin-argo-cd/src/api/index.ts#L95-L98) is the root cause since it is removing all filter params when not using namespaced apps

@kissmikijr can we get confirmation?

**Comment by QuadmanSWE** [comment]
This plugin broke for us when upgrading backstage and now shows every single application in argocd on every component which has any selector.
