### ISSUE TITLE
Upgrade to Support Node 18 Please

### ISSUE THREAD

**Issue by vanessap-aa** [RoadieHQ/roadie-backstage-plugins#1186]
## Feature Suggestion

Upgrade to Support Node 18 Please. My backstage app is using node 18, and in order to continue to develop and contribute to roadie plugins that my app uses, I need the plugins to depend on node 18. This will require testing all plugins. I am happy to help test the plugins we contribute to.

**Comment by Xantier** [comment]
not stale
