### ISSUE TITLE
Extended Security Insights Plugin to Support Github Advanced Security for Azure DevOps

### ISSUE THREAD

**Issue by mattemoore** [RoadieHQ/roadie-backstage-plugins#1208]
Currently the Security Insights plugin does not support GHAS for Azure Devops

## Feature Suggestion

For Azure DevOps users who have GHAS enabled this would be very useful as surfacing security issues is a key selling point for us for Backstage.

## Possible Implementation

Leverage the existing well known annotation from the Azure DevOps plugin: ` dev.azure.com/project-repo:` to get Project/Repo coordinates.  Use host, token and organization from azureDevOps entry in app-config.yaml to connect to proper devops organization where above Project/Repo is located.

## Context

Surface security issues on entity page.

**Comment by mattemoore** [comment]
No love for this feature request?

**Comment by Xantier** [comment]
Hi @mattemoore , I think this would be an excellent addition to the plugin itself. Would you be able to ship the implementation of this and we can then incorporate and release the new version with this included?

**Comment by mattemoore** [comment]
Unfortunately my current employer does not have a clear OSS contribution
process or allocation but I'll put this on my list of things we could do to
help the community and our own deploy of Backstage that I will bring to my
leadership team.  Hopefully I can get some type of percentage of team time
allocated to OSS contributions.
