### ISSUE TITLE
 [jira-plugin] Add support for multiple JIRA labels

### ISSUE THREAD

**Issue by aadmathijssen** [RoadieHQ/roadie-backstage-plugins#1242]
## Feature Suggestion

I would like the `jira/label` annotation to support _multiple_ labels instead of single label.

I suggest to do this by allowing space characters as separators (it is not possible to use lists in annotation values, only strings are allowed). As spaces are not allowed as label characters, this does not break any existing functionality.

## Possible Implementation

In essence, the implementation requires changing the label filters from "equals" to "has (one of)".

## Context

In our setup, we have JIRA projects that each serve multiple systems and components (Backstage system and component  entities).

The components in such a project can often be characterised by a single JIRA label. This can be represented by a `jira/project-key` and `jira/label` annotation.

However, the systems often contain multiple components, and as such can be characterised by the combination of the component's JIRA labels. This cannot be represented by a `jira/project-key` and `jira/label` annotation, as only single labels are supported. So the only choice is to leave out the `jira/label` annotation, which is not accurate.

As a workaround, we could use JIRA components to identify systems. However, this requires us to use both JIRA components and JIRA labels, which increases the maintenance burden and requires more discipline to keep sync. Also, in our setup, JIRA components are used mainly for billing purposes, not for logical divison.

**Comment by iain-b** [comment]
Hi @aadmathijssen, I know it's been a long time but I'm doing some work in the Jira plugin and I thought I'd roll in a fix for this. The current JQL clause is `AND labels in ("${label}")` but by removing the quotes the label annotation can be a csv list and used directly (Possibly this was the original intention). 

More generally, we'll be adding the ability to specify custom JQL by both props and annotations which would allow more flexible queries.
