### ISSUE TITLE
Use github apps integration to view insights

### ISSUE THREAD

**Issue by O5ten** [RoadieHQ/roadie-backstage-plugins#1271]
![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/3242379/06fbc759-9fe7-4c23-8250-7d9a6a633cbf)

## Feature Suggestion

Use the github apps integration if it exists in the application configuration to view contents of insights and make it configure not to do so if i should want to keep the existing behavior. 

## Possible Implementation

Use the integration if it exists, or make it configure not to do so if i want to keep the existing behavior. 

## Context

Today it seems that the insights plugin is making the user sign in to github in order to view repository insights. I'd like to avoid that as i have only setup github apps integration to authenticate towards github and use a SSO solution to authentiacate and authorize the user in backstage.

**Comment by jrtaylorJH** [comment]
Would like to second this request. Spotify tells us that it's due to a failure to use the updated Backstage authorization model, which should allow the plugin to retrieve the correct credentials

**Comment by jrtaylorJH** [comment]
![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/147415933/293ecd7a-9176-43f2-84e1-edb7029d8e7c)

See the above instructions directly from Spotify. I was able to get it going with the following scopes:

```defaultScopes: ["read:user", "read:org", "repo"],```

This fixed my issue.

**Comment by O5ten** [comment]
> I was able to get it going with the following overwrite to the default githubAuthApiRef within packages/app/src/api.ts:
> ```
>   ...
>   createApiFactory({
>     api: githubAuthApiRef,
>     deps: {
>       discoveryApi: discoveryApiRef,
>       oauthRequestApi: oauthRequestApiRef,
>       configApi: configApiRef,
>     },
>     factory: ({ discoveryApi, oauthRequestApi, configApi }) =>
>       GithubAuth.create({
>         configApi,
>         discoveryApi,
>         oauthRequestApi,
>         defaultScopes: ["read:user", "read:org", "repo"],
>         environment: configApi.getOptionalString('auth.environment'),
>       }),
>   })
> ];
> ```

This didn't work for me. I don't use GitHub oidc/oauth to authenticate to my backstage instance in the first place so I'm not sure how much effect it should have on my auth strategy with Azure Entra and having github apps as the github-integration.

**Comment by u-blavins** [comment]
Hi, I am also experiencing the same issues and would like to get this resolved. It is a neat plugin and it would be great to allow the GitHub app integration to carry forward!

p.s. the workaround did not also work for me :(
