### ISSUE TITLE
support the new backend system for http-scaffolder-plugin 

### ISSUE THREAD

**Issue by nia-potato** [RoadieHQ/roadie-backstage-plugins#1294]
support the new backend system for http-scaffolder-plugin

**Comment by hairmare** [comment]
Hi Roadies

It looks like this is blocking my update to today's 1.24 release. Getting `@roadiehq/scaffolder-backend-module-http-request` updated wrt to it's deps would probably also help me clean up several `yarn backstage-cli versions:check` complaints that aren't strictly related to the new backend.

just fyi, my main use case is that i create dependabot-able gha configs by calling the github api for concrete "latest" version info that i use in templates.

This is a feature that i would love to see doable in core. otoh, your action serves as the perfect template for "how to solve a simple problem in a generic way for many use cases" :smile:

**Comment by drodil** [comment]
Same goes for `@roadiehq/scaffolder-backend-module-utils`, would like to update the backend to new system but this is blocker

**Comment by hairmare** [comment]
This is fixed in `@roadiehq/scaffolder-backend-module-http-request` `^4.3.1` as per https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1325#issuecomment-2079684058
