### ISSUE TITLE
`@roadiehq/scaffolder-backend-module-utils` is not respecting transform option `noArrayIndent`

### ISSUE THREAD

**Issue by farism** [RoadieHQ/roadie-backstage-plugins#1301]
We noticed our styleguide linting checks failing on one of our projects after upgrading our version of `@roadiehq/scaffolder-backend-module-utils` above `1.13.1`, due to arrays becoming indented.

It looks like the root cause of the issue is [this change here](https://github.com/RoadieHQ/roadie-backstage-plugins/commit/3d55eb2fd4131c670405d5370b9bcb405ca3c168). The underlying yaml package was swapped from a package named [js-yaml](https://www.npmjs.com/package/js-yaml) to another one named [yaml](https://www.npmjs.com/package/yaml), but the [exposed yaml options](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/e2ec28fd71cfc60e801bb38a0a3ca1e67f245046/plugins/scaffolder-actions/scaffolder-backend-module-utils/src/types.ts#L21) are still referencing options from `js-yaml`

## Expected Behavior

Using `noArrayIndent` should prevent indentation on yaml arrays.

```yaml
my_array:
- item 1
- item 2
- item 3
```

## Current Behavior

```yaml
my_array:
  - item 1
  - item 2
  - item 3
```

## Steps to Reproduce

Use the `roadiehq:utils:jsonata:yaml:transform` action when scaffolding a template to transform some yaml array with the `noArrayIndent` option set to `true`. It will still indent the entries.

## Possible Solution

Existing options surfaced from the `js-yaml` package should be updated with a breaking change, or mapped to the `yaml` package with a minor version.

At the moment we have just pinned the version to avoid accidentally updating.

**Comment by timdoherty** [comment]
It looks as if [this test](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/e2ec28fd71cfc60e801bb38a0a3ca1e67f245046/plugins/scaffolder-actions/scaffolder-backend-module-utils/src/actions/jsonata/yaml.test.ts#L116) - while technically doing what it states 'should pass options to YAML.stringify' - does not verify that the options are correct.
