### ISSUE TITLE
backstage-plugin-prometheus - Wrong time format in Line/Graph X-Axis label

### ISSUE THREAD

**Issue by tonynguyen-ccl** [RoadieHQ/roadie-backstage-plugins#1306]
## Expected Behavior
The X-Axis label display correct time in the format of `HH:mm:ss`

## Current Behavior
It is displaying the month instead.

## Steps to Reproduce
- Just use the PrometheusGraph and you will see the bug. (Please note this is an old screenshot I took in January.)
<img width="1195" alt="image (1) copy" src="https://github.com/RoadieHQ/roadie-backstage-plugins/assets/115619462/bd882ac1-2613-4853-b6a0-0e31980be5b6">

## Possible Solution

- These 2 lines [here](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-prometheus/src/components/PrometheusGraph/PrometheusGraph.tsx#L193) and [here](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-prometheus/src/components/PrometheusGraph/PrometheusGraph.tsx#L143), the format should be changed to `HH:mm:ss` instead of capital `MM`

## Your Environment

- `@backstage/plugin-catalog-react` version:
- `@backstage/integration` version:

**Comment by jomeier** [comment]
Hi, yes that fix seems to work.
