### ISSUE TITLE
backstage-plugin-jira: capture events for analytics

### ISSUE THREAD

**Issue by yashoswalyo** [RoadieHQ/roadie-backstage-plugins#1314]
## Feature Suggestion
 

Using backstage analytics api to capture events for analytics
## Possible Implementation

Identified events to captured are:
- filters
- pagination
- button clicks
## Context

We are trying to collect analytics for actions performed in plugins, since we are using this plugin to display jira details, we would like to have analytics for some events in your jira plugin.

**Comment by yashoswalyo** [comment]
I am willing to submit PR

**Comment by Xantier** [comment]
Thanks @yashoswalyo,

Looking forward to reviewing!

**Comment by yashoswalyo** [comment]
@Xantier I have opened a PR for this issue.
