### ISSUE TITLE
[Rag-AI] Unauthorized 401 on query search api with authMiddleware enabled

### ISSUE THREAD

**Issue by tchapacan** [RoadieHQ/roadie-backstage-plugins#1328]
Thanks a lot for making this plugin opensource 🎉 

In continuation on the effort done in this PR https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1307 it seems there might be a part missing in the [searchClient.ts](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/rag-ai-backend-retrieval-augmenter/src/retrieval/retrievers/SearchClient.ts#L53) causing a **401 unauthorized  http error** when using **authMiddleware** while playing with the plugin.

It seems to come from this library `@roadiehq/rag-ai-backend-retrieval-augmenter`

## Expected Behavior

The `searchClient.ts` in `@roadiehq/rag-ai-backend-retrieval-augmenter` should be able to query backstage search api.

## Current Behavior

Here the error log : 

```json
{
    "level": "info",
    "message": "::ffff:127.0.0.1 - - [09/Apr/2024:13:04:51 +0000] \"GET /api/search/query?term=Which%20components%20own%20the%20platform%20team%20?&types[0]=software-catalog HTTP/1.1\" 401 12 \"-\" \"node\"",
    "service": "backstage",
    "type": "incomingRequest"
}
```

## Steps to Reproduce

- Configure backstage backend with an authMiddleware and register techdocs route with it:

`packages/backend/src/index.ts`

```js
...
const apiRouter = Router();
...
apiRouter.use('/techdocs', authMiddleware, await techdocs(techdocsEnv));
apiRouter.use('/rag-ai', authMiddleware, await ai(aiEnv));
...
```

- Use the AI Assistant plugin with the default setup (it seems to work as expected), but when investigating the **logs** here what can be found : 

```json
{
    "level": "info",
    "message": "::ffff:127.0.0.1 - - [09/Apr/2024:13:04:51 +0000] \"GET /api/search/query?term=Which%20components%20own%20the%20platform%20team%20?&types[0]=software-catalog HTTP/1.1\" 401 12 \"-\" \"node\"",
    "service": "backstage",
    "type": "incomingRequest"
}
{
    "label": "rag-ai-searchclient",
    "level": "warn",
    "message": "Unable to query Backstage search API for embeddable results.",
    "plugin": "ai",
    "service": "backstage",
    "type": "plugin"
}
{
    "level": "info",
    "message": "Received 0 results when querying augmentations from search.",
    "plugin": "ai",
    "service": "backstage",
    "type": "plugin"
}
```

## Possible Solution

Somehow like what have been already done in this PR i suppose https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1307 : 
- pass the `tokenManager` [defaultInitializer.ts](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/rag-ai-backend-retrieval-augmenter/src/defaultInitializer.ts) [SearchRetriever.ts](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/rag-ai-backend-retrieval-augmenter/src/retrieval/retrievers/SearchRetriever.ts) till it reach the `searchClient`
- add the issued token into the header : [searchClient.ts](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/rag-ai-backend-retrieval-augmenter/src/retrieval/retrievers/SearchClient.ts#L53)

```js
const url = `${await this.discoveryApi.getBaseUrl('search')}/query?term=${
      query.term
    }&types[0]=${embeddingsSourceToBackstageSearchType(query.source)}`;
    const { token} = await this.tokenManager.getToken();

    const response = await fetch(url, { method: 'GET', headers: {
      'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
    }});
```

I'd be happy to help and contribute with a PR if this issue make sense

## Context

Same context as this issue here https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1300 but with a different error message **http 401 unauthorized** when backstage search query api is triggered with authMiddleware from the `searchClient.ts`. 

For information the default setup of those two readme has been followed to try the plugin : [rag-ai-backend](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/backend/rag-ai-backend) and [rag-ai](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/rag-ai)

```sh
::ffff:127.0.0.1 - - [09/Apr/2024:13:04:51 +0000] \"GET /api/search/query?term=Which%20components%20own%20the%20platform%20team%20?&types[0]=software-catalog HTTP/1.1\" 401 12 \"-\" \"node\"
```
## Your Environment

- `@backstage`: 1.25.2
- `@roadiehq/rag-ai-backend-retrieval-augmenter`: 0.2.1
- `@roadiehq/rag-ai-backend`: 0.2.2
-  `@roadiehq/rag-ai-backend-embeddings-aws`: 0.2.1
-  `@roadiehq/rag-ai-storage-pgvector`: 0.1.1

**Comment by Xantier** [comment]
Thanks for the report @tchapacan !

Yeah, looks to be the case and your solution would likely fix it. Could you spin up a PR and we can get that merged?

**Comment by tchapacan** [comment]
My pleasure no problem, I'm gonna try to work on it today 🛠️

**Comment by kevinmartin** [comment]
I'm not sure this is fixed. I'm using the latest v0.3.0 version and still getting the above 401 errors with 0 results, using the new backend.

Sample code:
```ts
// rag ai plugin
backend.add(import('@roadiehq/rag-ai-backend'));
backend.add(
  createBackendModule({
    pluginId: 'rag-ai',
    moduleId: 'config',
    register(env) {
      env.registerInit({
        deps: {
          tokenManager: coreServices.tokenManager,
          logger: coreServices.logger,
          database: coreServices.database,
          discovery: coreServices.discovery,
          config: coreServices.rootConfig,
          indexer: augmentationIndexerExtensionPoint,
          pipeline: retrievalPipelineExtensionPoint,
          model: modelExtensionPoint,
        },
        async init({ tokenManager, logger, database, discovery, config, indexer, pipeline, model }) {
          const catalogApi = new CatalogClient({ discoveryApi: discovery });
          const vectorStore = await createRoadiePgVectorStore({
            logger: loggerToWinstonLogger(logger),
            database,
            config,
          });

          indexer.setAugmentationIndexer(await initializeOpenAiEmbeddings({
            tokenManager,
            logger: loggerToWinstonLogger(logger),
            discovery,
            catalogApi,
            vectorStore,
            config,
          }));

          pipeline.setRetrievalPipeline(createDefaultRetrievalPipeline({
            tokenManager,
            logger: loggerToWinstonLogger(logger),
            discovery,
            vectorStore,
          }));

          model.setBaseLLM(new OpenAI({
            model: 'gpt-4-turbo',
            temperature: 0.9,
            apiKey: config.getString('ai.embeddings.openai.openAIApiKey'),
          }));
        },
      });
    },
  })
);
```

Happy to create a new issue if needed.
