### ISSUE TITLE
Configure annotation for ArgoCD instance filter with multiple ArgoCD instances

### ISSUE THREAD

**Issue by adityasinghal26** [RoadieHQ/roadie-backstage-plugins#1345]
When configuring multiple ArgoCD instances using `@roadiehq/backstage-plugin-argo-cd-backend`, I am fetching multiple applications based on a label. As I have the same application in multiple ArgoCD instances, I would like to add an annotation in my `catalog-info.yaml` to filter based on instance configured (refer below image which shows applications from multiple instances).

<img width="1391" alt="image" src="https://github.com/RoadieHQ/roadie-backstage-plugins/assets/11928122/61693c51-e8d7-4c81-b229-141e5a0dd5cb">

## Feature Suggestion
This will allow me to pair Backstage components with ArgoCD applications, filtered by different ArgoCD instances.

## Possible Implementation
The possible annotation can look like below, where `<instance-name>` can be based on the configurations in `app-config.yaml`.

```
argocd/instance-selector: <instance-name>
```

We could also enrich this further if the selector could take an instance-array as below. 
```
argocd/instances: [<instance-name-1>, <instance-name-2>, <instance-name-3>]  
```

## Context
This would bring higher flexibility in fetching applications, purely from the instances that we want to. It will be helpful for us to achieve multi-tenancy based on multiple projects and environment ArgoCDs.

**Comment by pcgqueiroz** [comment]
This could be very useful. Do you plan to implement it?
