### ISSUE TITLE
add a gitlab pull request plugin

### ISSUE THREAD

**Issue by nia-potato** [RoadieHQ/roadie-backstage-plugins#1350]
i know we currently have the github pull request plugin, but it would be very useful for gitlab users as well. 

## Feature Suggestion

since alot of work would be just forking the github plugin and replacing API calls to use gitlab. i would like some guidance on what the potential flow to create such a plugin with any maintainer from roadie team. 

## Possible Implementation

fork the github pull request plugin, start replacing API calls to use gitlab.

**Comment by Xantier** [comment]
Thanks @nia-potato !

Yup, absolutely, that would be wonderful if you could contribute a plugin like that. I believe the best approach is likely to duplicate the current plugin as a new NPM package/folder in the plugins repository (while renaming it to Gitlab Merge Requests) and go forward from there. If you get the implementation started, we can have a discussion either here or on Discord about next steps if there are some roadblocks on the way.
