### ISSUE TITLE
New Backend is missing from the package exports 

### ISSUE THREAD

**Issue by 70mm1** [RoadieHQ/roadie-backstage-plugins#1363]
## Expected Behavior
When executing `yarn add @roadiehq/scaffolder-backend-module-utils/new-backend`, the install should work without errors.

## Current Behavior
`error Couldn't find package "@roadiehq/scaffolder-backend-module-utils/new-backend" on the "npm" registry.`

## Possible Solution
Edit the exports in package.json to:
```
 "exports": {
    ".": "./src/index.ts",
    "./new-backend": "./src/new-backend.ts",
    "./package.json": "./package.json"
  },
```

## Context
- trying to use the new Backend system of Backstage with the last release 1.15.0

**Comment by tam-pham-ts** [comment]
I also faced this issue

**Comment by Xantier** [comment]
Resolved on latest release
