### ISSUE TITLE
No dependency array means not reloading data correctly when params changes

### ISSUE THREAD

**Issue by DanielTibbing** [RoadieHQ/roadie-backstage-plugins#1370]
Hello 👋 

I'm building something that is using the argocd details card, I've run into the issue that as params changes (due to a new entity being set in the context) things are not reloaded with the new parameters. This is because there is no dependency array for the useAsyncRetry hook in the useAppDetails file:

https://github.com/RoadieHQ/roadie-backstage-plugins/blob/591413e83daca39908ca19ad27f4d631f3c42d26/plugins/frontend/backstage-plugin-argo-cd/src/components/useAppDetails.ts#L109

Is there any reason you've omitted the dependency array? If not, would it be possible to add the inputs (appName,
  appSelector,
  appNamespace,
  projectName,
  url) as dependencies?

/Daniel

**Comment by Xantier** [comment]
Thanks Daniel, there should be no reason for that omittance. Will  you open a pull request so we can get this fixed?
