### ISSUE TITLE
SelectFieldFromApi should allow the selection of multiple items

### ISSUE THREAD

**Issue by andreidum** [RoadieHQ/roadie-backstage-plugins#1466]
## Feature Suggestion
The current implementation allows the selection of a single item from a list. Please provide an option to allow the selection of more than one item. 

## Possible Implementation
The `Select` component provides some props for multiple selection https://react.dev/reference/react-dom/components/select#reference 

## Context
Users need a way to select more than one value from a list (eg. multiple clusters to which their component needs to be deployed). 
I'd like to be able to read those values and pass to a template.

**Comment by rmanik54** [comment]
Still relevant

**Comment by MadhuraApte222** [comment]
Is this planned in any upcoming releases? would be really helpful if its implemented
