### ISSUE TITLE
catalog-backend-module-okta: update config to include a schedule object

### ISSUE THREAD

**Issue by GoFightNguyen** [RoadieHQ/roadie-backstage-plugins#1634]
There are two confusing aspects of the config for `catalog-backend-module-okta`

1. The [config.d.ts](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/catalog-backend-module-okta/config.d.ts) does not match the expectation of `catalog.providers.okta` being a configArray, see [here](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/6de1b6cc8eed7d7a5c173c6ad1f4ff34d806c7b0/plugins/backend/catalog-backend-module-okta/src/module.ts#L73)

2. A schedule is expected to be defined like `catalog.providers.okta[0].frequency` ([see code](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/6de1b6cc8eed7d7a5c173c6ad1f4ff34d806c7b0/plugins/backend/catalog-backend-module-okta/src/module.ts#L80C9-L80C77)) rather than as a schedule object like `catalog.providers.okta[0].schedule`. The latter seems to be the common approach in backstage, see [this example](https://github.com/backstage/backstage/blob/f899a829e09d88a2e37bcd93c9fdca919878a6b8/plugins/catalog-backend-module-gitlab/config.d.ts#L49).

## Feature Suggestion

Specify the expectation of a schedule in the `config.d.ts` and support the frequently used approach of a schedule object.

## Context

`@roadiehq/catalog-backend-module-okta v0.10.2`, using the [new-backend-system as per the docs](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/backend/catalog-backend-module-okta#new-backend-system).

**Comment by Xantier** [comment]
This is resolved with https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1637
