### ISSUE TITLE
[Prometheus plugin] Issue with Prometheus Proxy Path in Backstage Configuration

### ISSUE THREAD

**Issue by hoanglecao** [RoadieHQ/roadie-backstage-plugins#1680]
Hi Team,

I am using the Prometheus plugin to integrate Backstage with Prometheus and set it up based on the guide from [Roadie](https://roadie.io/backstage/plugins/prometheus/?utm_source=backstage.io&utm_medium=marketplace&utm_campaign=prometheus).

## Expected Behavior

When configuring Prometheus with a cloud-hosted instance using the proxy settings, I expected the requests to be routed correctly through the defined proxy path to the Prometheus API. The API call should be successful, and I should be able to retrieve metrics using the provided Base64-encoded token

## Current Behavior

Despite correctly configuring the Prometheus proxy path and authorization header, the URL generated by Backstage is incorrect. Backstage generates a URL like /api/proxy/prometheus/api/query_range?query=up, whereas the correct URL should be /api/prom/api/v1/query?query=up. This results in a 401 Unauthorized error, even though the token is valid.

I have checked it with curl 
curl -H "Authorization: Basic <encoded-token>" https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/api/v1/query?query=up

Result :
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"up","instance":"localhost:9090","job":"prometheus"},"value":[1729006959.288,"1"]}]}}

I am not sure what I am missing or if I have misconfigured something. Any suggestions or ideas would be greatly appreciated.
## Steps to Reproduce

```yaml
app-config.yaml
proxy:
  '/prometheus/api':
    target: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom
    headers:
      Authorization: Basic <encoded-token>

```
```tsx
// packages/app/src/components/catalog/EntityPage.tsx
import {
  EntityPrometheusContent,
} from '@roadiehq/backstage-plugin-prometheus';
...
const serviceEntityPage = (
  <EntityLayout>
    ...
    <EntityLayout.Route path="/prometheus" title="Prometheus">
      <EntityPrometheusContent />
    </EntityLayout.Route>
    ...
  </EntityLayout>
);
Widgets Setup

// packages/app/src/components/catalog/EntityPage.tsx
import {
  EntityPrometheusAlertCard,  
  EntityPrometheusGraphCard,
} from '@roadiehq/backstage-plugin-prometheus';
...
const overviewContent = (
  <Grid container spacing={3}>
    ...
    <Grid item md={8}>
      <EntityPrometheusAlertCard />
    </Grid>
    <Grid item md={6}>
      <EntityPrometheusGraphCard />
    </Grid>
    ...
  </Grid>
);
```
## Context

This issue is blocking our integration with a cloud-hosted Prometheus instance. We're unable to retrieve metrics through the Backstage UI, and it affects our ability to monitor our application health and performance. Logs show a 401 Unauthorized error, but the same credentials work correctly when making direct curl requests

## Your Environment

-  "@backstage/plugin-catalog-react": "workspace:^",
- `"@backstage/integration-react": "workspace:^":
- "@roadiehq/backstage-plugin-prometheus": "^2.11.3",

**Comment by mariuszbozek** [comment]
Hi, please try new proxy config proxy.endpoints

https://backstage.io/docs/plugins/proxying/

**Comment by hoanglecao** [comment]
Hi @mariuszbozek,

Thanks for your support. Below is my current configuration (it already includes endpoints and reproduces the error). I missed including it in the Steps to Reproduce section.

proxy:
  endpoints:
    '/prometheus/api':
      # url to the api and path of your hosted Prometheus instance
      target: ${PROMETHEUS_URL}
      changeOrigin: true
      headers:
        Authorization: Basic ${PROMETHEUS_TOKEN}

**Comment by iamhalje** [comment]
same problem, even if prometheus works without authorization, and accepts all incoming requests, but not through a proxy from backstage

```
{
  "error": {
    "name": "AuthenticationError",
    "message": "Missing credentials",
    "stack": "AuthenticationError: Missing credentials\n    at DefaultHttpAuthService.credentials (/opt/backstage/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:150:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  },
  "request": {
    "method": "GET",
    "url": "/api/proxy/prometheus/api/rules?type=alert"
  },
  "response": {
    "statusCode": 401
  }
}
```

**Comment by iamhalje** [comment]
@hoanglecao with this parameter, working?

```
proxy:
  endpoints:
      '/prometheus/api':
      credentials: dangerously-allow-unauthenticated
```

**Comment by mariuszbozek** [comment]
> @hoanglecao with this parameter, working?
> 
> 
> 
> ```
> 
> proxy:
> 
>   endpoints:
> 
>       '/prometheus/api':
> 
>       credentials: dangerously-allow-unauthenticated
> 
> ```

This exactly works for me. I forgot to add 'dangerously-allow-unauthenticed' option (I work w local Prometheus instance it's ok for me). Before I used proxy without endpoints option and I received 401 (with or without token)

**Comment by hoanglecao** [comment]
Hi @mariuszbozek , @iamhalje ,

I am no longer getting the 401 Unauthorized error when using credentials with dangerously-allow-unauthenticated. However, I am facing another issue that may not be related to authentication. I will close the ticket. Thank you all very much for your huge support.

**Comment by and-arevalo** [comment]
Hi team,

I've opened this PR https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1857 to address the issue and eliminate the need for the `dangerously-allow-unauthenticated` workaround. Can you please take a look?
