### ISSUE TITLE
isolated-vm not up to date with latest release

### ISSUE THREAD

**Issue by Jenson3210** [RoadieHQ/roadie-backstage-plugins#1725]
In latest release there is an indication
> Scaffolder now supports Node.js v22
> The isolated-vm dependency has been upgraded to v5, which means the scaffolder now supports Node.js v22. It also means that running Scaffolder with Node.js v16 is no longer possible.

## Expected Behavior
App should start, using isolated-vm v5.

## Current Behavior
App is crashing with isolated-vm v4 when using latest version of backstage
https://github.com/laverdet/isolated-vm/blob/v5.0.1/src/isolate/environment.h
https://github.com/laverdet/isolated-vm/blob/v4.7.2/src/isolate/environment.h
![Screenshot 2024-11-19 at 14 34 33](https://github.com/user-attachments/assets/2105824a-a5f7-49ac-98c8-d63291641a5c)

## Possible Solution
bump `plugin-scaffolder-backend` usage in scaffolder related plugins.

## Workaround
in root, adding:
```json
"resolutions": {
    ...
    "isolated-vm": "^5.0.0"
  },
```
to the package.json file makes the app work again.

**Comment by benjdlambert** [comment]
Mentioned this in discord, but the thought here is that the modules shouldn't depend explicitly on the `@backstage/plugin-scaffolder-backend` package. Is there something that we're missing in OSS that we need to add?

**Comment by punkle** [comment]
@benjdlambert Its importing createTemplateAction from there.. but it shouldnt.. Ill get a pr up.

**Comment by punkle** [comment]
@Jenson3210 The release is going out now. Would you mind looking at retesting with the new versions of the plugins?

**Comment by Jenson3210** [comment]
@punkle sure. Will get back!

**Comment by Jenson3210** [comment]
@punkle all seems to be working after removing the resolution!

**Comment by punkle** [comment]
Brilliant thank you :)
