### ISSUE TITLE
List releases in GitHub repo

### ISSUE THREAD

**Issue by rodtan** [RoadieHQ/roadie-backstage-plugins#182]
## Feature Suggestion

Currently, releases are published to npm: https://www.npmjs.com/package/@roadiehq/backstage-plugin-jira . It would be nice to have them listed at https://github.com/RoadieHQ/backstage-plugin-jira/releases too, with a changelog if possible.

## Possible Implementation

Not sure how this is done with GitHub actions.

## Context

To view the changes between the releases, and also to use GitHub to notify me of any releases for this repo.

**Comment by Irma12** [comment]
@rodtan Sorry for delay for the response. This is now enabled for the plugins inside this repo. You can find the releases [here](https://github.com/RoadieHQ/roadie-backstage-plugins/releases ) :)
