### ISSUE TITLE
Cannot join discord 

### ISSUE THREAD

**Issue by karlhaworth** [RoadieHQ/roadie-backstage-plugins#191]
I get an error when trying to join your discord.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/58607256/130462685-83cf6c07-e89c-4f20-a9a8-c3b8a23fc4a0.png">

**Comment by Irma12** [comment]
@karlhaworth Can you try now? :)

**Comment by karlhaworth** [comment]
working! Thanks for the quick reply.
