### ISSUE TITLE
ArgoCD instance per cluster

### ISSUE THREAD

**Issue by karlhaworth** [RoadieHQ/roadie-backstage-plugins#193]
We have one argocd instance per cluster. The proxy solution mentioned doesn't seem scalable to us. We'd also need to add a path on catalog files for this to work properly.

The current kubernetes plugin finds an app across all clusters based on selectors. Could this plugin do something similar instead of having a proxy path added to each and every catalog-info file?

I started writing code to take over the argocd proxy URL on the backend to redirect the traffic based on what cluster an app resides on, but argocd plugin doesn't send cluster info making this harder and we'd rather work with you to make a solution than working in a silo.

All our argocd instances have URLs based on a pattern. Given the cluster name, we can determine the argocd instance URL.

**Comment by karlhaworth** [comment]
@tragiclifestories I think we cover that now. We don't use the kubernetes plugin anymore. Let me know if #270 covers this

**Comment by tragiclifestories** [comment]
This looks very nice! Thanks for all your work on this.
