### ISSUE TITLE
Argo Workflow support

### ISSUE THREAD

**Issue by tszngai** [RoadieHQ/roadie-backstage-plugins#194]
Hi Team, excellent work on creating these backstage plugins! Particularly we benefit greatly from the argocd plugin which displays the CD status of the application on dashboard. However the CI portion is missing. I understand people might be using Github action or Jenkins for CI but in our company we use Argo Workflow. Are there plans to create plugins for Argo Workflow? Thanks!

**Comment by tszngai** [comment]
Yes so what we are looking for is something similar to the argocd plugin, but for argo workflow.

It should have the ability to show the status of all workflows associated with the service and perhaps status of each workflow steps too.
Also show the output or error messages of the workflow in backstage.
What would be great is if we can add the ability to resubmit, retry and terminate a particular workflow from the backstage dashboard.

I am very new to backstage and I have only tried a few plugins so far. But I am happy to help wherever I can. Thanks!

**Comment by lukasmrtvy** [comment]
see https://github.com/backstage/backstage/issues/3746#issuecomment-843293011
