### ISSUE TITLE
Rendering html in readme.md in github-insights plugin

### ISSUE THREAD

**Issue by kcheriyath** [RoadieHQ/roadie-backstage-plugins#195]
## Issue

_Copying the issue from Backstage org._

Github insights plugin readme widget cannot render html markups. Readme containing html styling in github allow-lists are rendered as html markup code.

HTML mark-up in readme for a table is displayed as in the image below. The table is rendered correctly through github browser UI.

![image](https://user-images.githubusercontent.com/14891259/130259206-3ca2923b-cf2c-4139-a1ab-b952c3830361.png)

## Steps to Reproduce

1. Add an html table into readme.md
```
<table>
<tbody>
  <tr>
    <td>1</td><td>2</td>
  </tr>
  <tr>
    <td>3</td><td>4</td>
  </tr>
</tbody>
</table>
```

2. View readme through github (renders fine).
3. View readme from backstage (renders raw html).

## Context

Trying to add repos with https://allcontributors.org/ spec. All-contributors bot generates a contributors table in html format like here https://github.com/all-contributors/all-contributors. The html portions of this readme is not rendered correctly in backstage UI.

**Comment by martina-if** [comment]
https://app.clubhouse.io/larder/story/3878/rendering-html-in-readme-md-in-github-insights-plugin

**Comment by dtuite** [comment]
@martina-if those Clubhouse links don't appear to be working.
