### ISSUE TITLE
ArgoCD plugin expects missing JSON field

### ISSUE THREAD

**Issue by sam-robson** [RoadieHQ/roadie-backstage-plugins#199]
I've been having some problems with the Argo plugin when applications are syncing. 
Specifically I am receiving a `remote data validation failed` error as the JSON being validated lacks the [finishedState field on operationState](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backstage-plugin-argo-cd/src/types.ts#L13).

<img width="1064" alt="roadie-argo-plugin-error" src="https://user-images.githubusercontent.com/20035092/131100602-781c2aa1-f549-45b1-9a84-5405507e2ba3.png">

My first thought is that it makes sense that the value is not present, as the syncing operation hasn't finished. If so, it shouldn't be expected. I will write up a quick PR to remove this.

**Comment by martina-if** [comment]
Ch3877
