### ISSUE TITLE
Migrate all plugins to this monorepo

### ISSUE THREAD

**Issue by martina-if** [RoadieHQ/roadie-backstage-plugins#2]
We would like to move all the plugins from their single repositories into this monorepo.

We decided to do this to improve testability and development speed. By having the plugins in this repo together with a scaffolded app we can run cypress tests that make sure that updates in dependencies and new features don't break backstage apps for the community.

List of plugins we need to move here:

- [x] [github insights](https://github.com/RoadieHQ/backstage-roadie-plugins/issues/3)
- [x] [github pull request](https://github.com/RoadieHQ/backstage-roadie-plugins/issues/6)
- [x] [aws lambda](https://github.com/RoadieHQ/backstage-roadie-plugins/issues/7)
- [x] [jira](https://github.com/RoadieHQ/roadie-backstage-plugins/issues/74)
- [x] [datadog](https://github.com/RoadieHQ/backstage-roadie-plugins/issues/13)
- [x] [argocd](https://github.com/RoadieHQ/backstage-roadie-plugins/issues/8)
- [x] [travis ci](https://github.com/RoadieHQ/backstage-roadie-plugins/issues/11)
- [x] [buildkite](https://github.com/RoadieHQ/backstage-roadie-plugins/issues/12)
- [x] #168
- [x] [security insights](https://github.com/RoadieHQ/backstage-roadie-plugins/issues/10)

**Comment by kuangp** [comment]
Are you intending to also migrate https://github.com/RoadieHQ/backstage-plugin-jira ?

**Comment by Irma12** [comment]
@kuangp  Yes, thank you for putting this to our attention, we have missed it in the list.

**Comment by dtuite** [comment]
The migration is complete. If you're interested, we wrote about why we did this migration on the roadie.io blog.

https://roadie.io/blog/monorepo-plugins-migration/
