### ISSUE TITLE
Dependabot stats have low contrast

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/roadie-backstage-plugins#206]
I find the stats on the dependabot overview card to be a little difficult to read. Also the colors of High severity and critical severity are quite similar.

<img width="901" alt="Screenshot 2021-09-03 at 20 27 12" src="https://user-images.githubusercontent.com/562403/132056831-ddf228fe-6704-4c91-bf24-7bf7f3643434.png">

GitHub appears to use

Critical: `#cf222e`
High: `#bc4c00`
Moderate: `#bf8600`
Low: `#24292f`

Perhaps it would be good to stick with these colors for contrast and familiarity reasons?

**Comment by martina-if** [comment]
https://app.clubhouse.io/larder/story/3884

**Comment by Irma12** [comment]
> Low: `#24292f`

@dtuite I am just not sure about "Low" with dark theme, but others look good

**Comment by dtuite** [comment]
@Irma12 Good point. It should be just a matter of switching GitHub to dark mode and checking the colors they use for that case. We can use the same 2 sets of colors.
