### ISSUE TITLE
[github-plugin-insights] Enable multiple integrations 

### ISSUE THREAD

**Issue by Irma12** [RoadieHQ/roadie-backstage-plugins#215]
Currently, plugin will only look at the first integration for Github into cosideration. This is a problem for users having both GH and Github Enterprise integration provided. 

Proposed solution https://discord.com/channels/760879902391009330/760879902391009333/888281121413029888

**Comment by alexcurtin** [comment]
Any updates here?

**Comment by manusant** [comment]
I've been taking a look into the implementation and i believe that the perfect solution should be resolve the github api url form the github integration by matching the host config with the actual **entity source location**.

The source location (location from where the entity was retrieved) should be extracted from entity managed annotations **backstage.io/managed-by-origin-location** or **backstage.io/managed-by-location**.

More documentation on wellknown annotations can be found [here](https://backstage.io/docs/features/software-catalog/well-known-annotations).

@Irma12 please assign the issue to me. I'll submit a PR :)

**Comment by manusant** [comment]
PR opened #338. @Irma12 please have a look. and provide feedback. :)

**Comment by Irma12** [comment]
Closing this as a follow up of https://github.com/RoadieHQ/roadie-backstage-plugins/pull/338
