### ISSUE TITLE
Missing annotation error when loading datadog plugin

### ISSUE THREAD

**Issue by punkle** [RoadieHQ/roadie-backstage-plugins#216]
We had a user report that they saw the following error when on a component page when loading the datadog plugin:

```
Missing annotation
```

They said that the annotations were as follows. I am redacting the urls:

```
datadoghq.com/site: https://app.datadoghq.com/
datadoghq.com/dashboard-url: https://p.datadoghq.com/sb/<redacted>
```

**Comment by Irma12** [comment]
This issue has been solved.  Annotations for site should have been written in form of:

datadoghq.com/site: datadoghq.com

**Comment by martina-if** [comment]
Reopening until we fix the docs so it's very clear what this value needs to be (both README and marketing site)

**Comment by punkle** [comment]
I updated the roadie.io plugin documentation and the plugin readme to make this clearer.
