### ISSUE TITLE
Environment access plugin - Generic links plugin

### ISSUE THREAD

**Issue by Xantier** [RoadieHQ/roadie-backstage-plugins#265]
## Feature Suggestion

New plugin suggestion: Environment access.

## Possible Implementation

A simple plugin that gives the ability to configure links to running environments of an entity. For example a component could be running in AWS, on multiple accounts (staging, dev, prod) and having a direct linkage to those environments would be useful. Additionally on AWS specific items the possibility to add widely used switch role functionality linking to components. 

The plugin could be made generic possibly in a following way. 
#### Config options
Collection of account ID/baseurl and description pairs, with possible placeholders that can be replaced. For example:
```
environmentAccess: [
 {
    id: 'prod',
    description: 'Prod {{resource}}',
    link: 'https://signin.aws.amazon.com/switchrole?account=123456789012&roleName={{system}}_role_name&displayName="Prod {{resource}}"'
]
```
Where `resource` and `system` are interpolated from individual entity annotation.

#### Entity annotation
Entity annotation would be a 2-parter.
1. Identifying which links to display
2. Populating possible placeholders

For example (naming is not spot on for these):
```
environmentAccess/links: prod,dev
environmentAccess/placeholders: resource=My Service, system=My System
```

#### UI
List of links in some shape or form.

**Comment by kissmikijr** [comment]
Isn't it going to be just more complicated than using the built in links field on a component entity, however it seems much less manual work if we make it right.

https://backstage.io/docs/features/software-catalog/descriptor-format#links-optional
