### ISSUE TITLE
Is there some chance to add Okta as authenticator for githubpullrequest plugin? #needhelp #okta

### ISSUE THREAD

**Issue by jpiazza-asapp** [RoadieHQ/roadie-backstage-plugins#279]
We are implementing backstage in the company and we are trying to add plugins of github but seems like they relies only in. github authenticator, in our case we use Okta as standard. is there any way to make this plugins work with Okta authenticator too?
## Feature Suggestion
we accessing to github by Okta , which would be maybe great to add okta as authenticator 

currently  conf 
environment: development
  providers:
    okta:
      development:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_DOMAIN}

integrations:
  github:
    - host: github.XXX.dev
      apiBaseUrl: https://api.github.XXX.dev
      rawBaseUrl: https://raw.github.XXX.dev
      token: ${GHE_TOKEN}
## Context

we have made integration with github in fact all repo come from there , but seems like this plugin does not work if we don't put github authenticator , it ask me login, bur the curious is that i can access to the repo normally from backstage . is there any way that the plugin already take the integration of github as method of relies and not requires the githubauthenticator too?

![image](https://user-images.githubusercontent.com/82471878/141468217-e89e0aed-1c22-49ab-b3dc-7222c1c22de9.png)

**Comment by punkle** [comment]
Hi @jpiazza-asapp, Backstage has two integrations with Github, there is a the backend and the frontend. The frontend features is using the identity of the backstage user to use and interact with github resources. The frontend uses the OAuth protocol to retrieve a token for the user.

The backend also uses interacts with github resources, mostly to collect data for the purposes of the service catalog service. It can be configured to authenticate using a GITHUB_TOKEN as you have configured. Or it can be configured using a github app you create.

I think what you are ask is: "can the frontend features use the backstage backend credentials to retrieve the info to render the frontend features?". If this is your question, then yes it is technically possible, but there are a few advantages to contacting the github api on behalf of the user.

By way of an example. Suppose a user has access to a resource that other users do not. If the data was collected by the backend, it would become unmanageable to honor resource ownership correctly.

**Comment by martina-if** [comment]
@jpiazza-asapp Let me just add here that even if Github users are authenticated via Okta, configuring a Github Oauth App with a client and secret in backstage will work and transparently authenticate the okta users. This is because, if I am assuming the correct thing here, github will delegate the sign in to Okta during the oauth flow.

Would that help? 

What is the biggest limitation in your case?

**Comment by jpiazza-asapp** [comment]
in my case we followed the following link to provide login to the backstage https://backstage.io/docs/auth/okta/provider
I loged to backstage by Okta and when I try to go to the plugin of github , it shows me a popu window to login to github and when I did it it shows me error of login, i am confused cause I thought that already been loged by Okta would allow me to already be able to use the plugins without other login process
let me know if you need screenshoot

**Comment by martina-if** [comment]
Hi @jpiazza-asapp , That setup will give you some okta credentials but I think the plugin talks directly to github and for that it needs to negotiate github credentials. That is done with a Github Oauth App  that you need to configure in the same way as you did for Okta ([instructions here](https://backstage.io/docs/auth/github/provider)).

Is there any particular reason why this is more difficult in your organization?

**Comment by martina-if** [comment]
Hi @jpiazza-asapp I will close this issue since we believe the github oauth app credentials are still needed to communicate to the github API. But please feel free to re-open this issue if you think we should reconsider.
