### ISSUE TITLE
Add multi-Argo support (per component)

### ISSUE THREAD

**Issue by sam-robson** [RoadieHQ/roadie-backstage-plugins#289]
## Feature Suggestion

Accommodate components that live in multiple Argo instances (in the Argo plugin).

## Context

We have some environments that are split up by _cluster_, e.g. our production Backstage instance might live on ArgoInstance1 while staging might be on ArgoInstance2. 

I believe the current design of the Argo plugin assumes that each component will live on one instance, and so would only show one of the two environments in my Backstage example.

**Comment by Xantier** [comment]
Thanks for the suggestion @sam-robson! 

Yeah, I think it definitely makes sense to be able to annotate multiple Argos within the same entity. I believe we should probably use the developed argocd backend as a helper for this purpose, more specifically reusing the 'name' in the individual instance config from there.

Of the top of my head I can think of few approaches we could take here;
1. Extending the current model to take in arrays of items in annotations and using those based on their index
2. Creating a bit more dynamic annotations where the key value could have an indicator which environment specific config relates to.

Neither of these is really ideal and the nature of non-complex types in entity annotations makes it a bit tricky to make a clean solution for this. I think I'm more leaning towards the approach number 1 which would be easier to implement without breaking changes or big logic changes to annotation processing. 

That being said, this isn't on the immediate roadmap for us quite yet. @sam-robson would this be something you want to possibly contribute?

**Comment by sam-robson** [comment]
Sure, I'd be happy to contribute.

I'll explore the options a little more and get back to you with my thoughts.

**Comment by sam-robson** [comment]
After a bit of tinkering, it seems the current implementation (using the new [Option 2](https://roadie.io/backstage/plugins/argo-cd/#support-for-multiple-argo-cd-instances---option-2---argo-cd-backend-plugin)) _does_ support multiple Argos when using the `argocd/app-name` annotation. 

This isn't ideal for us; we've been using the `argocd/app-selector` annotation as we have a bunch of environments deployed in each cluster. I think I could extend the recent developments to accommodate this annotation without causing any backwards compatibility issues. 

Does this all sound sane to you?

**Comment by Xantier** [comment]
Thanks for taking a closer look at this. Yeah, I think it makes sense to add additional support for environments as well. If you draw up a PR we can take a look and iterate on that no problem. 

FYI @karlhaworth

**Comment by Xantier** [comment]
Closed as part of #306
