### ISSUE TITLE
Error occurred while fetching data. failed to fetch data, status 401: Unauthorized

### ISSUE THREAD

**Issue by CantHackTheHacker** [RoadieHQ/roadie-backstage-plugins#308]
Plugin is configured verbatim per instructions at https://roadie.io/backstage/plugins/argo-cd/.  The history card shows up with the message in the post title.   The network call shows it's trying to call http://localhost:7000/api/proxy/argocd/api/applications/{app-name} and fails with missing session information.  I have tested the token calling the ArgoCD api directly so I know the token is not the issue.  Does anyone have any insights on what I might be missing in the configuration?

**Comment by Irma12** [comment]
Hey @CantHackTheHacker, sorry you are experiencing issue and for taking a bit longer to respond. It's a bit slower pace as most of us are on vacations during the holiday time. The error does indeed lead me thinking token might be in bad format. Can you double check you have it in a form of `ARGOCD_AUTH_TOKEN=‘argocd.token=<token>’`.

**Comment by patoarvizu** [comment]
I'm also seeing this issue after following the plugin instructions verbatim, and I've confirmed that the environment variable is being set in that format. I've verified that the auth token I'm injecting is valid (based on [this Argo document](https://github.com/argoproj/argo-cd/blob/master/docs/developer-guide/api-docs.md) I found).

Is there anything else that I may be missing?

**Comment by CantHackTheHacker** [comment]
Unfortunately with the delay in response due to holidays and such, we went ahead and created our own plugin and works perfectly in Backstage.  Sorry I can't be of any further help with this plugin.

**Comment by Irma12** [comment]
@CantHackTheHacker I am glad you were able to overcome the issue with your plugin :)

@patoarvizu Could you check if the network call is also http://localhost:7000/api/proxy/argocd/api/applications/{app-name}?

**Comment by patoarvizu** [comment]
I have this behind a load balancer so it's not talking to localhost, but I can confirm from the dev tools console that the network call is made to `https://<my-load-balancer>/api/proxy/argocd/api/applications/<application-name>`

**Comment by Irma12** [comment]
@patoarvizu I have a bit of a trouble reproducing the issue but I know sometimes for other plugins it was a bit unclear how to format the token following instructions.

Token I use is in a format: 'argocd.token=mytoken12345'. I know in instructions it is noted as ARGOCD_AUTH_TOKEN='argocd.token=<token>' so just wanted to make sure you didn't include '<' and '>' in the token :)

**Comment by patoarvizu** [comment]
Hi @Irma12! Yes, I don't have the `<` `>` around the token. I've been working a little more on this since yesterday, and I've come across something strange that may be with how we're injecting the secret in our platform when deploying Backstage remotely where maybe the secret isn't being injected, or is empty, but I can confirm that I was able to make it work running locally, with the plugin configured to use the `Authorization: Bearer mytoken12345` header instead of the `Cookie` header, as the Argo documentation I pointed to above says, so if anything maybe at least this is helpful to update the plugin documentation.

I'll dig around a little more and I'll report back, I'd appreciate if we can keep the issue open for a little longer. Thanks!

**Comment by patoarvizu** [comment]
Ok, it was definitely an issue on our side where we were injecting a bad token. We can close the ticket now, thanks for your help!

If you think it would be valuable, I can offer to update the plugin instructions to add a note saying that the token can also be passed as an `Authorization` header 🙂

**Comment by Irma12** [comment]
@patoarvizu 🥳🥳 happy you got it working! Most definitely, every contribution would be highly appreciated. 

PS: Please make sure to include changesets after updating instructions (https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/CONTRIBUTING.md#creating-changesets). This helps us create release of the package afterwards 😇

**Comment by patoarvizu** [comment]
Thank you, will do!
