### ISSUE TITLE
Bugsnag Plugin Should Fetch All Projects 

### ISSUE THREAD

**Issue by KimboTodd** [RoadieHQ/roadie-backstage-plugins#312]
## Expected Behavior

The bugnsag plugin should make a request to the bugsnag api using pagination and return all available projects.

## Current Behavior

The [fetch request](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/6d7c927791118d0bb980207f3dfa4188de9ddfef/plugins/frontend/backstage-plugin-bugsnag/src/api/BugsnagClient.ts#L54) is not paginating request and is only returning 30 projects, which corresponds to the [default per_page](https://bugsnagapiv2.docs.apiary.io/#reference/projects/projects/list-an-organization's-projects).

## Steps to Reproduce

I cannot link you to an implementation. But if you try this plugin out with an organization that has more than the per_page count, you will see that only the number of projects in the per_page count is returned.

Steps to reproduce:
1. Set the plugin up in a backstage organization that has more than 30 bugsnag projects. 
2. Open the plugin in backstage for one of the projects that is not in the first 30 created. 
3. Observe that the plugin does not work.

Alternatively, as plugin developers steps to reproduce:
1. Alter [this](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/6d7c927791118d0bb980207f3dfa4188de9ddfef/plugins/frontend/backstage-plugin-bugsnag/src/api/BugsnagClient.ts#L54) line to use a per_page=1
2. Set up the plugin in backstage with an organization that has more than one bugsnag project
3. Go to the catalog entry of one of your components (except the first one created)
4. Observe the plugin doesn't work

## Possible Solution

- Could paginate in order to request all projects
- Could use the id of the project to [request only that project](https://bugsnagapiv2.docs.apiary.io/#reference/projects/projects/view-a-project) and not need to request all projects, also not needing to [find](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/6d7c927791118d0bb980207f3dfa4188de9ddfef/plugins/frontend/backstage-plugin-bugsnag/src/components/ErrorsOverviewComponent/ErrorsOverview.tsx#L54) the one that matches the notifier api key.

## Context

We're unable to use this plugin since it appears broken in many of our components, including our demo component backstage.

## Your Environment

- @backstage/plugin-catalog-react": "^0.6.0
- @backstage/integration": "^0.6.2

**Comment by Irma12** [comment]
@KimboTodd Sorry for taking a bit longer to get back to you. We were focused on some internal work and had to prioritise some other things, but hopefully with the latest version you will manage to get the plugin work. Thank you for reporting the bug, it has been extremely beneficial to learn this was happening.

There have been some additions, so you may see that we have introduced a new annotation which I would suggest you use
(bugsnag.com/project-name). In addition, as you have already noted, we have decided to make it optional for users to define number of results they would like to return, and this can be configured via app-config (resultsPerPage as you can see in README instructions). By default this will still be 30, but you can set this number to a different value (keep in mind Bugsnag has limitations for some api calls, so I believe 100 is max number you can set there).

**Comment by KimboTodd** [comment]
@Irma12 This worked for us. Thank you very much!
