### ISSUE TITLE
ArgoCD plugin fails with 404 when fetching app info

### ISSUE THREAD

**Issue by cooperbenson-qz** [RoadieHQ/roadie-backstage-plugins#355]
## Expected Behavior

The request doesn't 404 and I'm able to see the sync information

## Current Behavior

The request to ArgoCD returns a 404 and the ArgoCD card displays this
![image](https://user-images.githubusercontent.com/58954013/147970379-36839378-65fb-40ba-bb1e-7c4bba40f8cd.png)

## Steps to Reproduce

This happens to me if I upgrade to any version of the plugin > 0.13.2

## Possible Solution

Looking at the code and request logs, it's attempting to `GET /api/v1/applications/name/{app name}`, but according to the ArgoCD API documentation that doesn't exist. It's instead expecting `GET /api/v1/applications/{app name}`

## Context

I'm attempting to upgrade to v0.15.2 so I can upgrade other Backstage components, but the upgrade breaks the integration.

## Your Environment

- `@backstage/plugin-catalog-react` version: v0.6.9
- `@backstage/integration` version: v0.7.0
- ArgoCD server version: v2.2.2

**Comment by sam-robson** [comment]
Hey @cooperbenson-qz,

I think I might be responsible for this one! I'm working on a [PR](https://github.com/RoadieHQ/roadie-backstage-plugins/pull/356) which will hopefully fix the issue.

**Comment by Xantier** [comment]
Closing with #356. 
Release version 1.5.3 should have this fixed.
