### ISSUE TITLE
After using the post function getting 403 error even after using the right api 

### ISSUE THREAD

**Issue by aswathysen** [RoadieHQ/roadie-backstage-plugins#372]
## Expected Behavior

Create a new repository using an existing template repository, by providing the details of the new Repository as body for the POST

## Current Behavior

Current behaviour is throwing 403 error while running through backstage. 

## Your Environment

- `@backstage/plugin-catalog-react` version:
- `@backstage/integration` version:

**Comment by Xantier** [comment]
Thanks for the issue @aswathysen!

Could you possibly add a little bit more context on this one and we can then take a look at it. You could for example list out your setup and how we could reproduce this issue.

**Comment by martina-if** [comment]
Hi @aswathysen , are you still experiencing this issue? We need a few more details to understand what the problem is.

**Comment by martina-if** [comment]
Hi @aswathysen , since we don't have enough information to try to reproduce this problem and there's been some inactivity I will close this, but please if you are still experiencing this problem feel free to re-open this.
