### ISSUE TITLE
[Backstage Jira Plugin] A single team might own multiple projects

### ISSUE THREAD

**Issue by pavloskatsoulakis-wk** [RoadieHQ/roadie-backstage-plugins#373]
## Feature Suggestion
We would like the plugin to allow the representation of multiple JIRA projects for a single team.

## Possible Implementation
We were thinking that the project-key annotation could be an array of strings with the project keys.
On the presentation side, the component should draw tabs for each JIRA project when more than one keys are provided.

## Context
It is a very common use case for us for the same people or teams to belong/manage multiple JIRA projects.
We want to be able to depict this through backstage and not do hacks to accommodate it

**Comment by martina-if** [comment]
Hi @pavloskatsoulakis-wk , thank you for reporting this new feature. The focus of the team for the next couple of weeks is to migrate all plugins to react 17 and I doubt we will have a lot of time to work on new features in this plugin. We always welcome and appreciate pull requests from the community, is this something you or your team could contribute?
