### ISSUE TITLE
Backstage jira proxy's URL with undefined as project value

### ISSUE THREAD

**Issue by chapit-nicolas** [RoadieHQ/roadie-backstage-plugins#375]
Hi everyone.

I'm currently testing Backstage for my company, and I tried various integrations like Github, Jira, Jenkins and more. But I'm facing an issue with the Jira plugin. Maybe it's just a bad setup.

I already search any hint to help me to fix this, but all those places are a copy/paste of the jira plug-in's README.

## Expected Behavior

I guess the URL for the proxy should be "http://localhost:7007/api/proxy/jira/api/rest/api/latest/project/{PROJECT_KEY}"

## Current Behavior

In my component, I can see the Jira entity, but every time, it says "failed to fetch data, status 404: Not Found". When I look in the browser's console (network), I can see this 404, and this is the query "http://localhost:7007/api/proxy/jira/api/rest/api/latest/project/undefined". Why do I have "undefined"? Is it because the jira/project-key variable is not at the right place? Actually it's in the catalog-info.yaml, under metadata.

I tested my jira's token with postman and everything seem to be ok.

## Steps to Reproduce

Open any component,  and check the Jira entity tosee the 404 and in the browser's console (network) to find the url with undefined
![jiraEntity](https://user-images.githubusercontent.com/13436237/149337706-c14feec1-3527-42fb-ab6f-a6fc4144d4df.png)
![BrowserConsoleHeader](https://user-images.githubusercontent.com/13436237/149337984-4c45e354-7778-4fa8-a671-dfc1c7ba389c.png)
![BrowserConsoleResponse](https://user-images.githubusercontent.com/13436237/149338013-a1061074-499f-439d-8463-d6d201dc96a1.png)

## Your Environment

Everything was cloned/installed tuesday 11 january 2022, so it should be the latest version for everything.
- `@backstage/plugin-catalog-react` version: 0.6.10
- `@roadiehq/backstage-plugin-jira` version: 1.4.3

If some information is missing, let me know, I will do my best to provide them.

Thanks in advance.

**Comment by Irma12** [comment]
@chapit-nicolas Thanks for reporting the issue and I hope your experience with Backstage has been good so far. Regarding this specific issue, you mentioned you have set annotations under your metadata. Do you also have 'annotations' above? Yaml files are quite sensitive and sometimes you may have an indent extra or some line missing, which may lead to an issue. Can you double check your catalog-info.yaml file has annotations formatted this exact way?

<img width="890" alt="Screenshot 2022-01-14 at 15 31 15" src="https://user-images.githubusercontent.com/7230518/149532003-ade47b77-9f58-4c81-882e-2ab3cca62bf6.png">

**Comment by chapit-nicolas** [comment]
Hi @Irma12
Actually my company wants to see more about Backstage, so we have to prepare a presentation for our techleads and managers. So I guess it goes well :) 

Here the content of catalog-info.yaml at the project's root.
![catalog-info](https://user-images.githubusercontent.com/13436237/149534210-1e4f5ba3-968b-45c5-a035-6afe13eaf4a9.png)

I tested my file on http://www.yamllint.com/ and it's ok.

**Comment by Irma12** [comment]
@chapit-nicolas  File does seem fine 🤔 I have trouble reproducing the issue though. Can you try re-adding the component and see what happens?

**Comment by chapit-nicolas** [comment]
Sure.

**Comment by chapit-nicolas** [comment]
@Irma12 So I did 2 installations.

The first one from the repo my team built that contains only the app, so all files from the Backstage's repo were removed => same result: 404 and undefined in the URL
The second try was done with a fresh clone of Backstage's repo, without touching anything else than files in the new app for the jira plug-in's installation => same result 404 and undefined in the URL.

I made a video of all the process I did. Maybe there is something I'm doing wrong.
https://www.youtube.com/watch?v=cVsTHJofKwE
The video was made, based on the second try.

**Comment by chapit-nicolas** [comment]
A colleague may have understood the mistake...
The catalog-info.yaml at the project's root is a kind of template for templates to use to create new components.

Is that correct?

**Comment by Irma12** [comment]
@chapit-nicolas Well, practically yes. You can use that template to create new files in github or locally, which you need to import to your instnce afterwards. There you define annotations.

**Comment by chapit-nicolas** [comment]
Hi @Irma12 Thanks for the confirmation and the documentation. 
Everything is ok on our side now.

I will close this issue :)
Thanks again.

**Comment by Irma12** [comment]
@chapit-nicolas No problem, I am glad it worked, and hope you will enjoy your Backstage experience :)

**Comment by Rachid-Gharib** [comment]
Hey @chapit-nicolas  , I am facing the same issue as you and I am wondering if you could share how did you guys resolve it. Thanks

**Comment by chapit-nicolas** [comment]
Hello @Rachid-Gharib

I'm afraid that I won't be able to share anything... 
It's +1 year old and it was to show a new tool we could use in my company, but the idea was not selected, so I deleted all I had about this project and I don't remember anything...

I'm truly sorry... Wish you good luck.

**Comment by chapit-nicolas** [comment]
According to this comment https://github.com/RoadieHQ/roadie-backstage-plugins/issues/375#issuecomment-1014606371
It seems.

I red again all comments to see if anything was coming back. The only thing I can say is that our issue was that we were editing the wrong file, something like that. I can't tell much...

**Comment by autero1** [comment]
@Rachid-Gharib this could be due to the fact that Atlassian APIs return empty lists `404`s, etc if the auth header is invalid. For me, the issue was that my was `JIRA_TOKEN="ABCDExxxx`. Once I added `Basic` in the token (`JIRA_TOKEN="Basic ABCDExxxx`), it started working ok.
