### ISSUE TITLE
Support JIRA plugin on the org level not only component level

### ISSUE THREAD

**Issue by belaljuma** [RoadieHQ/roadie-backstage-plugins#415]
Currently, the JIRA plugin assumes a JIRA project for each component. This is not always the case as in my organization we have JIRA project for the whole product development, which comprises with a lot of components (microservices)
## Feature Suggestion
Support JIRA on the org level with an explicit filter to find/list issues on the component level

## Possible Implementation
Support JIRA on the org level. This includes for instance a side menu link, similar to docs and apis menu, and its JIRA page itself should allow filters to drill down to the component level issues

**Comment by martina-if** [comment]
Hi @belaljuma , we don't have a lot of time in the coming weeks to allocate to this plugin but we welcome contributors PRs. Is this something you could contribute?
