### ISSUE TITLE
Add Average Size Of PR to Pull Request Statistics

### ISSUE THREAD

**Issue by hyanghm** [RoadieHQ/roadie-backstage-plugins#461]
In an early development screenshot I found in [one Backstage discussion thread](https://github.com/backstage/backstage/issues/1808#issuecomment-671827496), there was a metric for Average Size of PR in Pull Request Statistics. We do not have it in the current implementation of the plugin. This is a very valuable metric. It helps teams analyze their size of PR's and figure out how to reduce time commitment for code reviews. 

## Feature Suggestion

Add Average Size Of PR to Pull Request Statistics

## Possible Implementation

Add the metric to the pull request statistics widget.

**Comment by kissmikijr** [comment]
Thanks for opening this issue! As we discussed on discord this is a good idea! I'll keep this ticket updated/linked to the PR as we will start progressing on this.
