### ISSUE TITLE
Argo CD Create/Delete Endpoints and Scaffolder Action

### ISSUE THREAD

**Issue by karlhaworth** [RoadieHQ/roadie-backstage-plugins#473]
## Feature Suggestion

Argo CD Create/Delete options for use with create plugin

**Is this something desired by the community?** If the contribution will be accepted, we can discuss open sourcing what we have already built. We would be moving from read-only to read/write permissions, however that can be controlled at the Argo CD level.

## Possible Implementation

American Airlines has create and delete endpoints built into the backend plugin that is open sourced.
We use the delete endpoint in a custom catalog component.
For the create endpoint, we incorporated it into a scaffolder action and the above mentioned custom catalog component.

We are proposing to open source the create and delete endpoints on the backend as well as the scaffolder action for Argo CD create.

## Context

Allowing Argo CD projects and applications to be created from the scaffolding create plugin.
Allowing deletion of projects and applications.

Right now due to code differences we manually pull-in contributed upstream code to our local and we'd prefer to contribute to open source.

**Comment by martina-if** [comment]
Hi @karlhaworth Thank you so much for proposing this!

I think this sounds very interesting and useful and from my point of view we would be very happy to accept it.

As you say, the only concern would be around security so as long as that can be controlled through Argo itself or configuration (and the plugin plays nicely when the permissions are not granted for some actions) it should be fine.
