### ISSUE TITLE
github-pull-requests HomePage components should be able to load more than 5 items

### ISSUE THREAD

**Issue by R-cen** [RoadieHQ/roadie-backstage-plugins#482]
The `HomePageRequestedReviewsCard` and `HomePageYourOpenPullRequestsCard` within the frontend `backstage-plugin-github-pull-requests` plugin are currently limited to showing only 5 PRs. This can be misleading for engineers who have more than 5 open PRs or review requests.

## Feature Suggestion

The maximum number of PRs should be configurable so users can view all their open PRs and review requests if they have more than 5. Increasing the number of PRs will however require some consideration in the design of the widget.

## Possible Implementation

I believe this can be updated if the `per_page` parameter is made configurable [here](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/35dd4497dcce7ef0d1e3f7e22d08b9521be682db/plugins/frontend/backstage-plugin-github-pull-requests/src/components/useGithubSearchPullRequest.tsx#L38) as the octokit docs indicate that a single request can request for a maximum of 100 PRs per page [here](https://octokit.github.io/rest.js/v18#search-issues-and-pull-requests)

**Comment by martina-if** [comment]
Hi @R-cen , what you are proposing makes a lot of sense. Would you be able to contribute this change?
