### ISSUE TITLE
Release 1.1.12 of backstage-plugin-github-insights is an empty package

### ISSUE THREAD

**Issue by jmgrimes** [RoadieHQ/roadie-backstage-plugins#49]
When trying to update plugins in my backstage instance this afternoon, I discovered broken imports after updating this plugin to 1.1.12.  1.1.11 still works properly.  According to the NPM package registry, the previous version of the plugin was about 200KB, and the new version is just over 17KB.  I think the package for the 1.1.12 version is broken or missing some pieces.

**Comment by irmasolakovic12** [comment]
That is definitely strange, thank you for reporting, we will check this @jmgrimes

**Comment by Irma12** [comment]
That is definitely strange, thank you for reporting and letting us know about the issue. We will check what could have happened @jmgrimes

**Comment by Irma12** [comment]
@jmgrimes version 1.1.14 is out and this shouldn't be an issue anymore. There were some problems with the published 1.1.12 version, so thank you once again for reporting this :)
