### ISSUE TITLE
http request action should log response body in case of an error

### ISSUE THREAD

**Issue by emilgelman** [RoadieHQ/roadie-backstage-plugins#500]
## Feature Suggestion

Currently, when the http-request action fails, the user will see the following in the scaffolder log:
`There was an issue with your request. Status code: ${res.status}`

It would be useful for the user to understand the failure reason by seeing the response body.

## Possible Implementation
https://github.com/RoadieHQ/roadie-backstage-plugins/pull/499

**Comment by alexef** [comment]
#499 was merged, this can be closed.
