### ISSUE TITLE
Use cross-fetch instead of axios

### ISSUE THREAD

**Issue by dweber019** [RoadieHQ/roadie-backstage-plugins#516]
## Expected Behavior
I would expect that the ArgoCD backend plugin is using cross-fetch to make requests, as it's the default for all plugins within the Backstage ecosystem.

## Current Behavior
Using axios https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/backstage-plugin-argo-cd-backend/package.json#L34

## Possible Solution
Replace axios with cross-fetch

**Comment by martina-if** [comment]
Hi @dweber019 , thank you for raising this. I would like to understand what is the biggest benefit for our users if we change this dependency? Also, is it causing problems in your Backstage instance?

**Comment by dweber019** [comment]
Hi @martina-if 
The users have to set the proxy like `HTTPS_PROXY` but most Backstage use will have https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md. It's an new dependency to manage beside cross-fetch, which does more or less the same.
I think it's the standard to use cross-fetch for Backstage plugins.
