### ISSUE TITLE
[Security-Insights] Dependabot card - "Bad credentials" error

### ISSUE THREAD

**Issue by mthad** [RoadieHQ/roadie-backstage-plugins#554]
Installed the security-insights plugin to display dependabot alerts but got an error "Bad Credentials"

## Expected Behavior

Dependabot card Should display list of dependabot alerts

## Current Behavior

Get  "Bad credentials" error message on Dependabot alerts card

## Steps to Reproduce

- Install security-insights plugin following the [instructions on Roadie webpage ](https://roadie.io/backstage/plugins/security-insights/)
- Create OAuth App from the GitHub Enterprise developer settings and configure the app-config.yaml according to [Backstage doc](https://backstage.io/docs/auth/github/provider#configuration)
- Start Backstage app (`yarn dev`)
- Once started go to the catalog and select a component
- Prompted for github login
- once authorized, Dependabot alerts card display "Bad credentials"

## Possible Solution

found this issue with similar error on another plugin that was fixed.

[Bad Credentials error when used with GitHub Enterprise](https://github.com/RoadieHQ/backstage-plugin-github-insights/issues/6)

## Context
Repositories hosted on Github Enterprise

## Your Environment
local app
OS:   Windows_NT 10.0.19042 - win32/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.17.0 (installed)

Dependencies:
  @backstage/app-defaults                         1.0.1
  @backstage/backend-common                       0.13.2
  @backstage/backend-tasks                        0.3.0
  @backstage/catalog-client                       1.0.2
  @backstage/catalog-model                        1.0.2
  @backstage/cli-common                           0.1.8
  @backstage/cli                                  0.17.0
  @backstage/config-loader                        1.1.0
  @backstage/config                               1.0.1
  @backstage/core-app-api                         1.0.1
  @backstage/core-components                      0.9.4
  @backstage/core-plugin-api                      1.0.2
  @backstage/errors                               1.0.0
  @backstage/integration-react                    1.1.0
  @backstage/integration                          1.2.0
  @backstage/plugin-api-docs                      0.8.4
  @backstage/plugin-app-backend                   0.3.31
  @backstage/plugin-auth-backend                  0.13.0
  @backstage/plugin-auth-node                     0.2.0
  @backstage/plugin-catalog-backend-module-github 0.1.2
  @backstage/plugin-catalog-backend               1.1.1
  @backstage/plugin-catalog-common                1.0.2
  @backstage/plugin-catalog-graph                 0.2.16
  @backstage/plugin-catalog-import                0.8.7
  @backstage/plugin-catalog-react                 1.1.0
  @backstage/plugin-catalog                       1.1.0
  @backstage/plugin-cost-insights                 0.11.26
  @backstage/plugin-github-actions                0.5.4
  @backstage/plugin-home                          0.4.20
  @backstage/plugin-org                           0.5.4
  @backstage/plugin-permission-common             0.6.1
  @backstage/plugin-permission-node               0.6.0
  @backstage/plugin-permission-react              0.4.1
  @backstage/plugin-proxy-backend                 0.2.25
  @backstage/plugin-scaffolder-backend            1.1.0
  @backstage/plugin-scaffolder-common             1.0.1
  @backstage/plugin-scaffolder                    1.1.0
  @backstage/plugin-search-backend-module-pg      0.3.2
  @backstage/plugin-search-backend-node           0.6.0
  @backstage/plugin-search-backend                0.5.1
  @backstage/plugin-search-common                 0.3.3, 0.3.4
  @backstage/plugin-search-react                  0.1.0
  @backstage/plugin-search                        0.8.0
  @backstage/plugin-sonarqube                     0.3.4
  @backstage/plugin-stack-overflow                0.1.0
  @backstage/plugin-tech-radar                    0.5.11
  @backstage/plugin-techdocs-backend              1.1.0
  @backstage/plugin-techdocs-node                 1.1.0
  @backstage/plugin-techdocs-react                0.1.0
  @backstage/plugin-techdocs                      1.1.0
  @backstage/plugin-user-settings                 0.4.3
  @backstage/release-manifests                    0.0.2
  @backstage/search-common                        0.3.4
  @backstage/test-utils                           1.0.1
  @backstage/theme                                0.2.15
  @backstage/types                                1.0.0
  @backstage/version-bridge                       1.0.1

**Comment by kissmikijr** [comment]
I think this will be something with the permissions of the github integrations on your backstage backend. Can you double check it has the correct permissions to list the dependabot alerts?
