### ISSUE TITLE
Security Insights giving error message `Could not resolve to a Repository with the name '<reponame>'`

### ISSUE THREAD

**Issue by Andy-medidata** [RoadieHQ/roadie-backstage-plugins#557]
## Expected Behavior

The dependabot widget should display correct values

## Current Behavior

I'm troubleshooting our integration to Github, our Github App config. It is working locally but not working in our live environment. So I tried opening an incognito window against my local dev environment. In a normal browser, it is working correctly, in the incognito window, I'm seeing the error message `Could not resolve to a Repository with the name '<reponame>'`. I noticed that there's a cookie in the browser `github-refresh-token` that is formatted differently between the two windows. The working window has `access-token.` prefixed to the token (and is much shorter), the incognito window does not have the prefix and a longer token. Both windows are on the same machine at the same time.

## Steps to Reproduce

install the Security Insights plugin and enable the dependabot widget per [install instructions](https://www.npmjs.com/package/@roadiehq/backstage-plugin-security-insights).

Our Github integrations (from app-config.yaml):
`integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
auth:
  environment: development
  providers:
    okta:
      development:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_DOMAIN}
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}`

Open in a chrome browser, point to [component](http://localhost:3000/catalog/default/component/activities), it works correctly
Open in a chrome incognito window, point to [component](http://localhost:3000/catalog/default/component/activities),  you get the error `Could not resolve to a Repository...`.

## Your Environment

- `@backstage/plugin-catalog-react` version: "^1.0.0"
- `@backstage/integration` version: "^1.2.0"

**Comment by kissmikijr** [comment]
@Andy-medidata Is this issue still happening ?

**Comment by Andy-medidata** [comment]
yes it is. I'll run another test to confirm this afternoon

**Comment by kissmikijr** [comment]
If it is still an issue can you provide some more details, possible screenshots which card are we talking about exactly? 
After opening it in incognito did you login again to github and still doesn't work ?

**Comment by Andy-medidata** [comment]
will do, in the middle of another story, may take me a day to get back to that branch...

**Comment by Andy-medidata** [comment]
here's a screenshot of the error
![Dependabot Widget](https://user-images.githubusercontent.com/44985584/183129967-4defe6bc-fc8f-4913-88a3-40b045d78475.png)
:

**Comment by Andy-medidata** [comment]
just duplicated in the incognito window, I'm scanning through the logs looking for error messages that seem relevant...

**Comment by Andy-medidata** [comment]
the only messages I've found so far:
`[1] 2022-08-05T17:30:54.071Z backstage info ::1 - - [05/Aug/2022:17:30:54 +0000] "GET /api/catalog/entities/by-name/component/default/api-gateway HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" type=incomingRequest
[1] Request not identified as belonging to a backstage's background process
[1] Request not identified as belonging to a backstage's background process
[1] Request not identified as belonging to a backstage's background process`

I'm not certain the "Request not identified" are related to this or not...

**Comment by Andy-medidata** [comment]
just double checked I've implemented the setup steps: [https://www.npmjs.com/package/@roadiehq/backstage-plugin-security-insights](https://www.npmjs.com/package/@roadiehq/backstage-plugin-security-insights)

for implementing the dependabot widget, I did not implement the Security Insights widget/page because we do not have it enabled.
