### ISSUE TITLE
Customises ArgoCD Project and Applications creation

### ISSUE THREAD

**Issue by ale-conekta** [RoadieHQ/roadie-backstage-plugins#577]
Actually , the plugin allow to create the ArgoCD Project from zero and the ArgoCD Application. 
These option not allow you to use and existing ArgoCD Project and then with the actual ArgoCD Application created it does not allow to give the correct path where values.yaml lives.
For example, if you have the following structure:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/88718697/177045589-39b67b0b-acd4-49a0-a307-6858403daa62.png">

## Feature Suggestion
Would be nice to add an option to create or not the Argocd Project. On the other hand, would be nice when the ArgoCD Application is created it allow you to give details like: 

- source.repositoryUrl: **git**, **helm**
- source.kind: **Directory**, **Helm**, **Kustomize**, **Plugin**

## Possible Implementation

Add new actions like:
- **argocd:create-application**
-  **argocd:delete-application**
- **argocd:sync-application**
- **action: argocd:create-project**
- **action: argocd:delete-project**

## Context
Theses option allows us to add different custom step to create and deploy application on ArgoCD using Backstage with custom values.yaml

**Comment by Xantier** [comment]
Thanks @ale-conekta ,

Those sound like good enhancements to the plugin. Would this be something you'd be willing to contribute and provide a PR for?
