### ISSUE TITLE
[plugin/security-insights] Dependabot Widget should filter vulnerabilities closed as `fixed`

### ISSUE THREAD

**Issue by isand3r** [RoadieHQ/roadie-backstage-plugins#615]
## Expected Behavior

The security insights dependabot widget should show the current number of outstanding vulnerabilities on my github repository (by severity).

## Current Behavior

The dependabot widget shows a count of all vulnerabilities, even if they are closed as `fixed`.

## Steps to Reproduce

1. Setup backstage with this plugin.
2. Configure a catalog entry that points to a github repository with some dependabot alerts closed as `fixed`.

## Possible Solution

I think [this line](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-security-insights/src/components/DependabotAlertsWidget/DependabotAlertsWidget.tsx#L100) is only taking into account vulnerabilities being closed as `dismissed` - some additional logic should filter out `fixed` vulnerabilities.

## Context

Example Screenshots:
Widget:
<img width="384" alt="Screen Shot 2022-08-08 at 9 04 11 AM" src="https://user-images.githubusercontent.com/6620402/183462360-f0a01727-6b51-44bc-9413-5a56984a6c43.png">
Github:
<img width="971" alt="Screen Shot 2022-08-08 at 9 05 02 AM" src="https://user-images.githubusercontent.com/6620402/183462530-0ffed544-fbb1-4942-b6c5-1847ff722909.png">

## Your Environment

- `@backstage/plugin-catalog-react` version: `^1.1.2`
- `@backstage/integration` version: `^1.1.2`

**Comment by Xantier** [comment]
Thanks @isand3r!

Good find, I think it makes sense to enhance the filtering to remove fixed items from the list as well. Would you like to contribute this functionality to the repo?

**Comment by isand3r** [comment]
@Xantier for sure, either myself or one of my colleagues will try to contribute something soon!

**Comment by isand3r** [comment]
looks like someone else got to this! thank you!

**Comment by punkle** [comment]
That was me. Soz. Didn't see this ticket 😔

**Comment by punkle** [comment]
Thanks for closing.
