### ISSUE TITLE
[plugin/security-insights] Dependabot Widget should show more than 100 open alerts

### ISSUE THREAD

**Issue by punkle** [RoadieHQ/roadie-backstage-plugins#636]
Dependabot Widget should show more than 100 open alerts

## Expected Behavior

If I have more than 100 dependabot alerts on my repository in github the security insights plugin should report on them all.

## Current Behavior

It only shows the first 100 alerts.

## Steps to Reproduce
Create at least 100 alerts on a single project and open a component that shows the dependabot widget on the entity page.

## Possible Solution

Add paging to the graphql query.

## Your Environment

- `@roadiehq/backstage-plugin-security-insights` version: 2.0.6

**Comment by dotboris** [comment]
This is still a problem and we are currently suffering from it.
