### ISSUE TITLE
[plugin/catalog-backend-module-okta] Group membership is not synced

### ISSUE THREAD

**Issue by sole0bserver** [RoadieHQ/roadie-backstage-plugins#640]
## Expected Behavior

Not only groups and users per se are synced from Okta, but group membership is synced and visible as well.

## Current Behavior

Currently I'm testing it with Dev Okta instance. There are two groups and two users. I added users to these groups, and see no errors in backend's logs, but every group is showed as having no members. Overall, entities appear in the catalog.

## Steps to Reproduce

Add required parameters to app-config catalog.providers.okta, add code to catalog.ts. Run ```yarn dev```, see entities are synced but groups are memberless.

## Possible Solution

TO be honest, I'm lacking TypeScript dev experience. I do see in sources that ```listUsers``` is called on every Group, so I came to a conclusion that this is supposed to work.

## Your Environment

Backstage 1.5.0

**Comment by kissmikijr** [comment]
Just to make sure could you send me the relevant part of your catalog.ts? I am curious of the order of the providers

**Comment by kissmikijr** [comment]
Are you using namingStrategies in your setup in your catalog.ts ?

**Comment by sole0bserver** [comment]
@kissmikijr I’m on vacation right now and don’t have laptop with me. I recall I copied most of catalog.ts in this repo. I presume the issue might be in the part where the plugin creates new group: in the yaml file members array is passed as-is, instead of something like members: members

**Comment by kissmikijr** [comment]
@sole0bserver No worries enjoy! :) 
I actually tried to repro this on my local setup with a developer okta account and wasn't able to do repro the issue. The members, groups got added correctly with the correct relations.
I was only able to repro this when I used a different namingStrategy config setting for the providers. Basically if you use it you need to use the same naming strategy for the Group provider's user naming strategy as you use for the User provider.

When you get back and will be able to try it out feel free to get back to me!: ) I'd love to help and figure out what's going on!

**Comment by martina-if** [comment]
Hi @sole0bserver , since we couldn't reproduce the issue and this has been stale for sometime I am going to close this. If you are still experiencing problems even when changing the naming strategies please reopen this issue and we'll be happy to help.
