### ISSUE TITLE
Other AWS Authentication methods (IRSA & Instance profiles)

### ISSUE THREAD

**Issue by andrewgkew** [RoadieHQ/roadie-backstage-plugins#665]
## Feature Suggestion

Currently according to your docs this plugin can authenticate with access and secret keys, but AWS can authenticate with other mechanisms depending on where your service lives. Two which I think should be considered are

1. AWS IAM Roles for Service Accounts (EKS)
2. Instance profiles (EC2)

## Context

The context for this request is that rather than sharing (creating) a specific IAM user to have access and then needing to share access/secret keys is better to (and recommended) to rather use roles which is achieved by using the 2 methods above depending on your platform.

**Comment by kissmikijr** [comment]
Hey! Thanks for opening this, which plugin are we talking about exactly? We have a couple ones. Could you please add the plugin(s) that you are referring here?

**Comment by martina-if** [comment]
@andrewgkew gentle ping about the question above ^ :) Which plugin were you referring to?

**Comment by andrewgkew** [comment]
Hey @martina-if @kissmikijr 

sorry for the delay. I think I was referring to this plugin

https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/backend/backstage-plugin-aws-auth

Thanks
