### ISSUE TITLE
Filter out archived repos from GitHub Pull Requests

### ISSUE THREAD

**Issue by klaraward** [RoadieHQ/roadie-backstage-plugins#668]
I would like PRs from archived repos to not show up in the GitHub Pull Requests overview

## Feature Suggestion

This could either be done by always filtering away archived repos, or by having this as an option.

**Comment by kissmikijr** [comment]
Hey! Which plugin are we talking about? Based on the opened PR to the backstage/backstage repo it seems this issue should be in the backstage/backstage repo. I believe our github plugins should already filter out archived repos. 
This is our github pull requests plugin: https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-pull-requests

**Comment by martina-if** [comment]
Hi @klaraward , as I mentioned in #669 I think you are refering to the [pull request board plugin](https://github.com/backstage/backstage/tree/master/plugins/github-pull-requests-board) so I will close this issue but please reopen it if we assumed wrong.

**Comment by klaraward** [comment]
I think you assume right, I'm a longterm backstage user but have never worked on any of the plugins :)
