### ISSUE TITLE
Display Assignee in GitHub Pull Requests view

### ISSUE THREAD

**Issue by klaraward** [RoadieHQ/roadie-backstage-plugins#669]
Display Assignee in GitHub Pull Requests view

## Feature Suggestion

There is already author and reviewer, but the lower right corner might be the avatar of the assignee if there is one, 
this would make it easier to pick an unassigned PR to work on.

**Comment by martina-if** [comment]
Hi @klaraward I suspect you are talking about this plugin instead https://github.com/backstage/backstage/tree/master/plugins/github-pull-requests-board so it's better that you open an issue in the https://github.com/backstage/backstage repository instead. 

I will close this one, if you think I am wrong please feel free to reopen it and provide a screenshot or a little bit more information of what you are looking for and we'll be happy to help.
