### ISSUE TITLE
ArgoCD Plugin: Weird UI problems when clicking the refresh button

### ISSUE THREAD

**Issue by jpilowsk-te** [RoadieHQ/roadie-backstage-plugins#671]
https://user-images.githubusercontent.com/110424269/192888763-1fce5e92-c009-4b1f-aa07-ec890f95f4b3.mp4

## Expected Behavior

When the user pushes the refresh button in the details cards, the details card content should re-render with the same CSS classes it rendered the first time it loaded

## Current Behavior

When the refresh button is clicked and the ArgoCD data loads again, there are new CSS classes and there are weird CSS rules that change the margins, fonts, backgrounds, etc.

## Steps to Reproduce

Example of the original rendered HTML vs the secondary rendered HTML

<img width="1553" alt="Screen Shot 2022-09-28 at 2 09 25 PM" src="https://user-images.githubusercontent.com/110424269/192889437-f4c68e6c-a419-4f45-b12e-f18f144ed37c.png">

## Possible Solution

* Upgrading to @mui/material 

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.1.4
- `@backstage/integration` version: 1.3.1

**Comment by Xantier** [comment]
Thanks for opening the issue @jpilowsk-te . The video looks to be in some proprietary format so unfortunately that is not working. What plugin is this affecting?

**Comment by martina-if** [comment]
Hi @jpilowsk-te , indeed it looks like something is wrong there. Is this something you can take a look at and perhaps provide a pull request for?

**Comment by jpilowsk-te** [comment]
> Thanks for opening the issue @jpilowsk-te . The video looks to be in some proprietary format so unfortunately that is not working. What plugin is this affecting?

This is the ArgoCD plugin (https://roadie.io/backstage/plugins/argo-cd). Sorry I wasn't more clear

**Comment by david-behnke** [comment]
We have the same problem with other Roadie plugins.

Example with GitHub Insights Plugin and its `EntityGithubInsightsReadmeCard`
![image](https://user-images.githubusercontent.com/42135073/205975848-6bb37cf4-2bab-4e5d-ba43-d3e13dc11186.png)

**Comment by jpilowsk-te** [comment]
@david-behnke, the problem for us turned out to be multiple classname generators in the project. MUI V4 has [an FAQ about this issue](https://mui.com/material-ui/getting-started/faq/#v4-why-arent-my-components-rendering-correctly-in-production-builds). The `yarn.lock` file was forcing multiple version of `@material-ui/core` library. Try running `yarn list @material-ui/core`. If you get more than one version, there's the problem. If not, look at the other possible reasons in the FAQ

**Comment by david-behnke** [comment]
Thanks to @jpilowsk-te I could solve this issue.
Thank you very much :+1:
