### ISSUE TITLE
Datadog private dashboard support

### ISSUE THREAD

**Issue by saada** [RoadieHQ/roadie-backstage-plugins#673]
The plugin works fine with public dashboards and graphs. There doesn't seem to be a way to include private dashboards?

## Feature Suggestion

Add a way to embed private dashboards.

## Possible Implementation

Perhaps a backend plugin that takes in a configuration for a Datadog token which can then fetch the requested dashboard via the backend proxy?

## Context

I would like to embed private dashboards without sharing a public URL.
My suggested implementation is probably too complex. We can brainstorm for better ways to do this in this thread.

**Comment by martina-if** [comment]
Hi  @saada !! 👋  Good to see you around here :)

I think this is a great suggestion. The quickest way we found to integrate these dashboards with backstage was to use these public urls but it's not great so I think your suggestion is probably the best approach.

Is this something you could contribute?

**Comment by saada** [comment]
wow @martina-if  what a small world :) 

Happy to contribute it when it's possible! Unfortunately it looks like the Datadog team has not built this feature yet.
I reached out to the Datadog team and they're prioritizing this feature eventually through their API. I'll update here when it's possible. Not sure if we should keep this ticket open. Or we could close and reopen later, up to you 🥲 

<img width="313" alt="Screen Shot 2022-09-26 at 2 30 55 PM" src="https://user-images.githubusercontent.com/1087987/192810275-17022035-d54e-40b7-9eb4-a015627b52c0.png">

Take care

**Comment by martina-if** [comment]
Thanks for checking with them @saada . Since this has been on our radar for quite a while let's close it for now and reopen when it's possible to build it.
