### ISSUE TITLE
[catalog-backend-module-okta]: filter organizations

### ISSUE THREAD

**Issue by GoFightNguyen** [RoadieHQ/roadie-backstage-plugins#686]
My okta implementation has multiple LDAP organizations, such as Technology and Finance.
As I do not wish to ingest users/groups from Finance, the ability to ingest only from Technology would be helpful.
An added pro of this approach would mean, depending on the type of sign-in resolver used, that only Technology folx could log in.

**Comment by punkle** [comment]
@GoFightNguyen could you check if the groupFilter and userFilter options meets your needs here?

**Comment by martina-if** [comment]
Hi @GoFightNguyen hopefully the new filtering options can help you with this so I will close this issue. If you find that you need additional functionality please don't hesitate to re-open this issue with more information or even contribute a pull request.

**Comment by GoFightNguyen** [comment]
Ack'ing that this worked. Thank you
