### ISSUE TITLE
[catalog-backend-module-okta]: filter groups by name

### ISSUE THREAD

**Issue by GoFightNguyen** [RoadieHQ/roadie-backstage-plugins#687]
## Feature Suggestion

An Okta implementation might have multiple types of groups within an Okta/LDAP organization.
As backstage enables building developer portals, it is possible all those types of groups need neither ingestion nor access to the developer portal.

For example, an Okta organization named ABC might contain groups prefixed with `dev_` and `marketing_`.
But only the `dev_` groups should be in the developer portal.

**Comment by punkle** [comment]
@GoFightNguyen could you check if the groupFilter meets your needs here?

**Comment by GoFightNguyen** [comment]
Sorry I missed this. Although I still lack the time to try this, the filter options appear to address the need. Thanks

I'm going to close this Issue
