### ISSUE TITLE
[scaffolder-backend-module-aws]: ECR repo creation - Add Image scanning configuration

### ISSUE THREAD

**Issue by akundrock** [RoadieHQ/roadie-backstage-plugins#695]
## Feature Suggestion

Hello!
As part of the AWS ECR repo creation workflow I would like to optionally enable "Image Scanning on push". This feature is available through AWS and provides useful information on vulnerability scanning for container images

## Possible Implementation

Add a flag to the ECR create repo command to enable image scanning and add the necessary config to the input to the aws/client-ecr library.

## Context
The file can be found here: 
plugins/scaffolder-actions/scaffolder-backend-module-aws/src/actions/ecr/create.ts

The needed config input is documented here:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ecr/interfaces/createrepositorycommandinput.html#imagescanningconfiguration

Note that I would be willing to pick up this work if it is approved/desired as a feature
Thanks!

**Comment by kissmikijr** [comment]
It sounds like a good addition and we would love it if you could contribute it! Feel free to ask for any help if you need it!
