### ISSUE TITLE
[catalog-backend-module-okta]: Backstage Groups created with Okta ID making it difficult to reference for general users

### ISSUE THREAD

**Issue by laxmaneppalagudem** [RoadieHQ/roadie-backstage-plugins#697]
The current Okta group and user sync plugin code create new backstage group and user entities with Okta ID as the primary identifier for referencing them rather than using the friendly name. This [line](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/catalog-backend-module-okta/src/providers/OktaGroupEntityProvider.ts#L98) makes the group entity name as Okta ID something on the lines of _00ft66tTgr39DBWBHrt2_. Now when users want to add this group in catalog-info.yaml file they have to add this ID which is difficult to remember instead of the more commonly used okta profile name like _team_eng_ that is assigned to the title field of the group entity [here](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/catalog-backend-module-okta/src/providers/OktaGroupEntityProvider.ts#L99)

## Feature Suggestion

It would be ideal if users could refer to group entities using the more commonly user profile name as set in the title field instead of needing them to memorize Okta IDs in order for backstage to recognize owners.

## Context

I'm setting up backstage for our internal use and want to enable users to provide group entity owners in the catalog-info.yaml files for taxonomy purposes. Ideally these group entity names are the same as the okta group names used in various other systems internally.

**Comment by kissmikijr** [comment]
Actually there is a prop that you can use to configure how should it name the generated entities. I updated the README of the plugin to try to explain it in a bit more detail. https://github.com/RoadieHQ/roadie-backstage-plugins/pull/699

But the tldr is you can use the strip-domain-email to use the email
```
  const userProvider = OktaUserEntityProvider.fromConfig(oktaConfig[0], {
    logger: env.logger,
    namingStrategy: 'strip-domain-email',
  });
  const groupProvider = OktaGroupEntityProvider.fromConfig(oktaConfig[0], {
    logger: env.logger,
    userNamingStrategy: 'strip-domain-email',
    groupNamingStrategy: 'kebab-case-name',
  });
```

**Comment by laxmaneppalagudem** [comment]
hey @kissmikijr thanks for providing this info. i tried the method mentioned in the readme and works for the most part with a small change needed in the `groupProvider` invocation. `groupNamingStrategy` doesn't exist in the constructor [here](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/catalog-backend-module-okta/src/providers/OktaGroupEntityProvider.ts#L57).  it instead expects a argument of name `namingStrategy`

using the below snippet does the trick:


const groupProvider = OktaGroupEntityProvider.fromConfig(oktaConfig[0], {
    logger: env.logger,
    namingStrategy: 'kebab-case-name',
    userNamingStrategy: 'strip-domain-email',
  });

thanks for the help. appreciate it.
