### ISSUE TITLE
Dependabot Table does not work with github enterprise server

### ISSUE THREAD

**Issue by szubster** [RoadieHQ/roadie-backstage-plugins#698]
## Expected Behavior

Dependabot table works with github enterprise, same as dependabot widget (which works).

## Current Behavior

<img width="324" alt="image" src="https://user-images.githubusercontent.com/603853/198535195-24d449ea-3f90-40ea-afc5-ec9cd18a9870.png">

## Steps to Reproduce

Connect backstage with github enterprise server
Add entity with source set to custom github server
dependabot widget works ok, but dependabot table tries to contact github.com

## Possible Solution

Add same logic to check github server, as widget has, to the table

## Context

We try to use dependabot plugin :)

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.2.0
- `@backstage/integration` version: 1.3.2

**Comment by kissmikijr** [comment]
Thanks for reporting this, it definitely should work with github enterprise!
