### ISSUE TITLE
Bug: catalog-backend-module-okta null group descriptions

### ISSUE THREAD

**Issue by sfc-gh-jtsuyemura** [RoadieHQ/roadie-backstage-plugins#706]
## Expected Behavior
Okta groups are ingested into the catalog

## Current Behavior
When an OKTA group is `initially` created WITHOUT a `description`, the OKTA API will return a `null` value in the description field. This results in a `Policy Check Failed` error since the entity's description value expects a `string`

### Create an Okta Group create with no `initial` "description"

<img width="1035" alt="Screen Shot 2022-11-06 at 5 29 48 PM" src="https://user-images.githubusercontent.com/82846263/200208507-aa5ec95b-97f5-49b2-82e5-39ca7db46ad6.png">

NOTES: If you `edit` the group to add a `dsecription`, then remove it later, the API will return a blank string `""` as expected, and the plugin will work. Only a problem when the Okta group is initially created without a description and the description is never updated.

### Call Okta Groups Api to see `null` description

<img width="407" alt="Screen Shot 2022-11-06 at 5 35 34 PM" src="https://user-images.githubusercontent.com/82846263/200209019-12f48eba-0f78-4900-b90e-b73304c0c6db.png">

### Backstage backend Error log
```
2022-11-07T01:31:48.355Z catalog-module-okta warn Policy check failed for group:default/new-group-no-description; caused by Error: Malformed envelope, /metadata/description must be string type=plugin entity=group:default/new-group-no-description
```

## Possible Solution

https://github.com/RoadieHQ/roadie-backstage-plugins/blob/a500eaebeeacd414b61e0b32128d0a374bba9e0a/plugins/backend/catalog-backend-module-okta/src/providers/OktaGroupEntityProvider.ts#L100

Suggested Change + Updating Tests
```
 description: group.profile.description || '', 
```

## Your Environment

- `@backstage/plugin-catalog-react` version: @roadiehq/catalog-backend-module-okta@^0.3.0

**Comment by sfc-gh-jtsuyemura** [comment]
Feel free to assign to me. I believe I have a fix ready.

**Comment by kissmikijr** [comment]
Awesome! Thanks for taking this! :)

**Comment by sfc-gh-jtsuyemura** [comment]
Hey @kissmikijr I don't think I have the correct permissions to create a brach -> PR even though I'm assigned the issue :)

**Comment by punkle** [comment]
You would need to create a fork of the repo and create a branch on the fork. Then you can create a pull request against this repo.
