### ISSUE TITLE
New releases should notify Discord and Twitter

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/roadie-backstage-plugins#71]
Currently, users of our plugins don't really have a way to know when new releases are availalbe.

Can we send an automated discord message to our Discord server when we release a new version? This should work just like the one for Backstage.

Can we send a Tweet from the Roadie Twitter account when we release a new version?

[ch3458]

**Comment by martina-if** [comment]
https://app.clubhouse.io/larder/story/3458/new-releases-should-notify-discord-and-twitter

**Comment by martina-if** [comment]
https://app.clubhouse.io/larder/story/3458/new-releases-should-notify-discord-and-twitter

**Comment by martina-if** [comment]
[Ch3458]

**Comment by martina-if** [comment]
https://app.clubhouse.io/larder/story/3458
