### ISSUE TITLE
Enable Generic Credentials for Github Connectivity

### ISSUE THREAD

**Issue by victormorfin97** [RoadieHQ/roadie-backstage-plugins#719]
## Feature Suggestion
Give more flexibility to the way how ocktokit object is getting created to gain connectivity for Github to gather information.
## Possible Implementation
I have to possible approaches to accomplish this one:
### Pass a custom ocktokit object
This could be accomplish by creating an optional property to the components that make use of the object or if we want to avoid repeating the process for each component maybe creating a provider that could receive an instance of ocktokit and from there it could be available for each component
### Add optional configuration on app-config.yaml
We can also add optional configuration to app-config.yaml file with the ocktokit configuration that we want our object to be created, this will allow the users to customize the ocktokit object by configuration.

## Context
The way that the plugin is creating ocktokit objects is by gathering configuration from githubAuthApiRef, like this:
```typescript
    const auth = useApi(githubAuthApiRef);
    const token = await auth.getAccessToken(['repo']);
    const octokit = new Octokit({ auth: token });
```
And is awesome, but in some implementations of Backstage like ours in Expedia, we dont use Github as an auth provider but we so have like a generic admin account with a lot of permissions on Github. So, if we try to adopt your plugin each amount of time backstage prompts a required login to Github and is giving bad user experience from our customers. So if we change or add more customization to the way how you are initializing ocktokit object we can improve the current experience.
Im pretty sure that maybe others adopters are dealing or could deal with the same issue since not all are using Github as an auth provider.

**Comment by stephenmuss** [comment]
Would be great to see support for Github apps. I'd like to be able to show security insights etc to people within the organisation that don't necessarily have an account in Github.
