### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by Gaardsholt** [RoadieHQ/roadie-backstage-plugins#72]
It would be great if we could get a release notes/changelog on what has changed in a new release and if we need to update something in our installation.
Similar to what backstage is doing: https://github.com/backstage/backstage/releases/tag/release-2021-07-08

**Comment by dtuite** [comment]
@Gaardsholt yes. We agree. We are currently in the process of migrating all our plugins into this monorepo. Release notes are one of the features which will be much easier to add once that's done.

**Comment by martina-if** [comment]
https://app.clubhouse.io/larder/story/3459

**Comment by Irma12** [comment]
@Gaardsholt We have been worked on this and now you can see releases https://github.com/RoadieHQ/roadie-backstage-plugins/releases with the notes attached to them :)
