### ISSUE TITLE
GitHub Pull Request widgets and a custom query.

### ISSUE THREAD

**Issue by djl197** [RoadieHQ/roadie-backstage-plugins#739]
I am using the GitHubPullRequests Home widget and can see the ability to override the `query `parameter to modify the Github Query.

I am trying to set the query based on the metadata.name field - for example:
`is:open is:pr archived:false team-review-requested:${entity.metadata.name}`

The idea being that I could use the widget on a `group` entity page and list all of the PRs assigned to that team.
However I am struggling to get a dynamic query string into the EntitySwitch statement:

```
<Grid item xs={12}>
  <HomePageRequestedReviewsCard title="Pending Review Requests" query=<?>/>
</Grid>
```

Any ideas if this is possible or does the EntitySwitch logic mean this is not possible?

**Comment by kissmikijr** [comment]
I'll need to check this, it is certainly possible that in the current implementation it won't work in a group page, but I like the idea to add it there!

**Comment by djl197** [comment]
My thought was that on a User Page it could be added to show the Pending PRs for that individual - if the metadata.annotation.name for the User (or a different field) within the entity could be used to lookup in GitHub.

The same for the Group Page - find all reviews pending on a specific team within Github - when you could match to the metadata.name or maybe use github.com/team-slug

Then the homepage can use the current default query string.  
I have been exploring - but struggling to get the entity object.

**Comment by djl197** [comment]
Continuing my exploration - and I am confused (first time with Backstage plugins) - It appears that on a HomePage I dont have access to the entity object (via useEntity or useAsyncEntity).

The same component on a Component Page works fine - trying to work out how I can detect if I am on one page or the other.
If not I will create 2 new widgets that are embeddable cards that can be used on Entity pages.

**Comment by kissmikijr** [comment]
Oh, yea, the homepage has no access to the entities. I believe it is not under the entity context or something. 
I think it is cleaner if we create separate components for this!
