### ISSUE TITLE
Add support for GHE

### ISSUE THREAD

**Issue by jwlawrence** [RoadieHQ/roadie-backstage-plugins#76]
It appears that these plugins won't work with github enterprise instances. If that's not the case can you add docs for how to configure the correct auth? If that is the case, I think that it's worth investing in adding support. I assume many of the users of backstage will be running private github installs and being able to pull insights from it would be very powerful.

**Comment by Irma12** [comment]
Hi @jwlawrence, integrating GitHub Enterprise with Backstage requires a bit of additional effort. Can you verify you have followed instructions ( https://backstage.io/docs/plugins/github-apps) and let us know about the issues you are experiencing with the plugins?

**Comment by jwlawrence** [comment]
Thanks @Irma12 I'm just starting to evaluate backstage so I'm not familiar with all the nuances yet. Following the guide did the trick, sorry for the inconvenience.

**Comment by tszngai** [comment]
Hi team I'm running into same issue. Do we know what minimum version of GHE is required to work with backstage? Thanks!

**Comment by tszngai** [comment]
> Hi @jwlawrence, integrating GitHub Enterprise with Backstage requires a bit of additional effort. Can you verify you have followed instructions ( https://backstage.io/docs/plugins/github-apps) and let us know about the issues you are experiencing with the plugins?

Hi @Irma12  I wonder why we need to create a github application to authorize the plugins (the Github insights and Github pull request plugins). Since we've already provided a github (enterprise) token in the app-config.yaml, can't the plugins just use that token to auth with Github? Thanks in advance.
