### ISSUE TITLE
Sidebar of components under code insights erratic behaviour.

### ISSUE THREAD

**Issue by NivethaJayaveeran** [RoadieHQ/roadie-backstage-plugins#762]
The sidebar of the component increases its width while moving into code insights entity layout page. 

## Expected Behavior

The sidebar of the component should not increase its width on the github insight page loading. The Grid spacing should be adjusted in such a way that on page load the cards should auto adapt to screen size.
The size of the card should adjust to the screen size.

## Current Behavior

The screenshot attached is an example of already implemented github insight plugin in our application, while loading the page the cards that get displayed moves to the sidebar depending on the screen size. We tried pull in this plugin into our application but the issue still persists.

![image](https://user-images.githubusercontent.com/102040284/206712302-5f6803f1-0cd6-46b6-b88d-c6fc8638fcc6.png)

The card space is reflected in the sidebar.
![image](https://user-images.githubusercontent.com/102040284/206712434-ebdee50d-4a47-48cd-8966-45a6deee0be4.png)

The backstage github insights plugin version used in our application is:
@roadiehq/backstage-plugin-github-insights": "^2.0.0"
## Your Environment

- `@backstage/plugin-catalog-react` version: 1.1.1
- `@backstage/integration` version: 1.2.1

**Comment by kissmikijr** [comment]
Thanks for reporting this, I'm not sure I understand fully the issue. Does this plugin page ruins the sidebar? Is the sidebar pinned to be open? or is it opens on hover?
