### ISSUE TITLE
Github-insights needs bearer token

### ISSUE THREAD

**Issue by mist3r3** [RoadieHQ/roadie-backstage-plugins#780]
Instead of just calling the request for readme:
url/readme using basic auth it should be using bearer token, else it just won't work.

## Expected Behavior

200 at api

## Current Behavior

I get 404:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/16564723/208438819-f2a2f6ff-1f97-47ea-a213-5c589d19dfbe.png">

## Steps to Reproduce

Install the plugin and link it to a repo

## Possible Solution

Add bearer token use

 ## Context

I can't get the readme file.

## Your Environment

- `@backstage/plugin-catalog-react` version:
- `@backstage/integration` version:

**Comment by mist3r3** [comment]
Just to be clear, I'm using github apps. I've set it into the auth part of the app-config.yaml

**Comment by kissmikijr** [comment]
Hm, this is strange because I'm pretty sure the current plugin works for me with github app. Do you still run into this issue? I suspect it might be some kind of permission issue ?

**Comment by martina-if** [comment]
@mist3r3 did you figure out if it was related to the GH app permissions? Since we didn't hear back from you I will close this but feel free to reopen it if you think there is still a bug in the plugin.

**Comment by miguelpuiggarcia** [comment]
I got similar issue, when integrating the plugin using

I get: 
<img width="1135" alt="mpg" src="https://user-images.githubusercontent.com/58427697/220899475-5c315462-03b6-4125-95b5-183a2f313b46.png">

My app config is:
```
integrations:
  github:
    - host: github.com
      apps:
        - $include: backstage-app-credentials-github.yaml
```

that file contains:

```
appId: xxx
clientId: Ixxxx
clientSecret: xxxxx
webhookSecret: +6e(xxxx
privateKey: |
```
