### ISSUE TITLE
markdown plugin to support multiple source providers

### ISSUE THREAD

**Issue by punkle** [RoadieHQ/roadie-backstage-plugins#791]
The homepage markdown plugin currently only supports markdown sourced from github.

## Feature Suggestion

It would be great if it could retrieve markdown from other sources, like bitbucket, s3 etc. It would even be nice if it could support any data from the url readers.

## Possible Implementation

I dont have a suggestion for a possible implementation.

**Comment by kissmikijr** [comment]
Yea, would be cool, though the current markdown plugin is only a frontend plugin. I think this more general markdown plugin with the usage of urlreaders could be achieved if we'd create a backend part for the plugin.
