### ISSUE TITLE
Missing auth token to ArgoCD Api in serviceLocatorUrl requests

### ISSUE THREAD

**Issue by ivashc** [RoadieHQ/roadie-backstage-plugins#796]
Enabling API requests authentication breaks the ArgoCD frontend plugin due to missing auth token.

## Expected Behavior

Api requests have an auth token if API authentication is enabled.

## Current Behavior

Requests to api endpoint /api/argocd/find/name/{componentName} do not have bearer token and fails with error 401

## Steps to Reproduce

1. Enable API authentication using this [document](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md)
2. Install roadiehq/backstage-plugin-argo-cd and roadiehq/backstage-plugin-argo-cd-backend using official howto's
3. Enable auth check in api router configuration: `apiRouter.use('/argocd', authMiddleware, await argocd(argocdEnv));`

## Possible Solution

Is it possible to add Authorization header to the serviceLocatorUrl requests [here](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-argo-cd/src/api/index.ts#L185), similar to what we have in [fetchDecode](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-argo-cd/src/api/index.ts#L79) method

## Context

Not able to enable API auth for Argocd API endpoint.

## Your Environment

- `@roadiehq/backstage-plugin-argo-cd-backend@^2.6.2`
- `"@roadiehq/backstage-plugin-argo-cd@^2.2.1"`

**Comment by kissmikijr** [comment]
Thanks for reporting this, yes this should definitely be supported by the plugin! I'll see how can we put this on our roadmap to fix it.

**Comment by cursedcoder** [comment]
@martina-if @kissmikijr  here's the PR #1080
