### ISSUE TITLE
app-selector does not support all argocd label constraints

### ISSUE THREAD

**Issue by wpessers** [RoadieHQ/roadie-backstage-plugins#812]
## Feature Suggestion
Add support for all possible argocd label constraints.
_See the selector string command option at: https://argo-cd.readthedocs.io/en/latest/user-guide/commands/argocd_app_list/#options_
`-l, --selector string        List apps by label. Supports '=', '==', '!=', in, notin, exists & not exists. Matching apps must satisfy all of the specified label constraints.`

## Possible Implementation

The argocd frontend and backend plugin both need some changes to accomodate this.
I would propose to give the user the option to specify a label constraint in the first part of the annotation placed on the component. 

Of course some changes will need to be made to the way the annotations is being parsed by the argocd plugin. 
- For the frontend, that would be [here](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-argo-cd/src/api/index.ts#L118). Notice the hardcoded '`=`' sign:
`${encodeURIComponent(k)}=${encodeURIComponent(params[k] as string)}`

- For the backend, roughly the same thing occurs [here](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/backstage-plugin-argo-cd-backend/src/service/argocd.service.ts#L123).

I would propose to make these hardcoded `=` signs into variables, with a default value of '`=`'. So as to not introduce a breaking change for users who are already using the app-selector in the way it is set up today.

**Example:**
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: myservice
  annotations:
    argocd/app-selector: in component=myservice
```
This should translate to the following argocd API endpoint:
https://myinstance.argocd.be/api/v1/applications?selector%20in%20component%3Dmyservice
Which will return all argocd applications that have the `component: myservice` label among their labels.

## Context

We have one central argocd instance that manages applications accross clusters, for each environment. For example, let's say we have a service _MyService_ . We then have a separate argocd application per environment: dev-myservice-, stg-myservice and prd-myservice. These all run on a separate cluster, but are managed by that one argocd instance. For the corresponding component in backstage, I would like to display all these environment-specific services together in the argocd-plugin entities.

It seems to me that the argocd/app-selector annotation was provided for this usecase. However, the way this is currently implemented ([frontend](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-argo-cd/src/api/index.ts#L118), [backend](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/backstage-plugin-argo-cd-backend/src/service/argocd.service.ts#L123)) is hardcoded to use the '`=`' argocd label constraint. This label constraint will only return argocd applications that have exactly **all** of the specified labels. In my case, our applications often have multiple labels. To illustrate in the example that would look like this for the dev environment:
```
labels:
  component: myservice
  argocd.argoproj.io/instance: applications-dev 
  environment: dev
```
If I add an annotation on my component `argocd/app-selector: component=myservice`, I would expect this to be picked up by the argocd plugin. But due to the hardcoded '`=`' constraint, I would have to instead add **all** labels to the annotations like so: `argocd/app-selector:   component=myservice,argocd.argoproj.io/instance=applications-dev,environment=dev`

With the presence of environment-specific labels in our applications, you can probably see how this becomes an issue when we want to get the argocd application for each environment. Looking at our example in the test environment:
```
labels:
  component: myservice
  argocd.argoproj.io/instance: applications-tst 
  environment: tst
```

There seems to be no way of making the `argocd/app-selector` annotation work here, because of the strict matching of the '`=`' constraint.

**I'm already working on a fix for this issue, so would be willing to contribute.**

**Comment by martina-if** [comment]
Hi @wpessers , first of all, thank you for a great issue write-up! We appreciate you taking the time to write all the details and volunteering to contribute this enhancement! 🎉 

The changes proposed sound very useful and reasonable to me. My main concern would be backwards compatibility but it seems you got that covered so I think we would love for this to be contributed.

I also want to ping @karlhaworth in case he has any feedback on this.

**Comment by martina-if** [comment]
related to #289

**Comment by karlhaworth** [comment]
> My main concern would be backwards compatibility but it seems you got that covered so I think we would love for this to be contributed.

That was my only feedback. We don't use labels this way, so no other feedback. Thanks.

**Comment by dfl-aeb** [comment]
Any news on this topic? We could also really use this feature :)

**Comment by diegoluisi** [comment]
Up..
