### ISSUE TITLE
backstage-plugin-home-markdown support for github enterprise

### ISSUE THREAD

**Issue by chrissi517** [RoadieHQ/roadie-backstage-plugins#816]
I want to use the mark-down plugin and it seems that it does not support github enterprise.

Request URL: https://api.github.com/repos/.../.../contents/README.md
![image](https://user-images.githubusercontent.com/98878963/211767775-05ba718d-4232-4a65-b4e7-2beee920b20c.png)

Is it possible to implement it?

Used Version:
"@roadiehq/backstage-plugin-home-markdown": "^2.5.1",

**Comment by martina-if** [comment]
Hi @chrissi517 can you provide more information about what the issue is please? What error are you seeing? How have you configured authentication towards github enterprise?

**Comment by chrissi517** [comment]
Authentication is configured in app-config.yaml
integrations:
  github:
    - host: xxxx
      apiBaseUrl: xxxx
      token: xxx
      
 I have several other plugins running with git hub enterprise, so the github enterprise integration should work.
 
 **Error Description:**
 
![image](https://user-images.githubusercontent.com/98878963/217505558-d5101ae7-53ec-41ad-a894-12db92da7741.png)

At the network tab on chrome (F12 - Network), I see that the README.me could not be loaded, because it refers **not** the apiBaseUrl that I added to the integrations.github

![image](https://user-images.githubusercontent.com/98878963/217506435-6dee3fa3-33e5-4090-b66e-96255c7a7478.png)

**Comment by punkle** [comment]
@chrissi517 you might be best placed to help us with this issue. Would you be in a position to provide a pull request to fix it?
