### ISSUE TITLE
Github Insights Plugin Breaks When Environments Are Not Found

### ISSUE THREAD

**Issue by sarahpmedeiros** [RoadieHQ/roadie-backstage-plugins#817]
## Expected Behavior

When environments are not found, show the working insight cards. Handle the failure more gracefully, show an error message in the card or don't show the environments card.
## Current Behavior
![Screen Shot 2023-01-11 at 12 14 43 PM](https://user-images.githubusercontent.com/14253893/211873424-b70bb48c-affd-40a7-8dec-f9e5470be320.png)

## Steps to Reproduce
When hitting /environments our enterprise github instance returns `{
    "message": "Not Found",
    "documentation_url": "https://docs.github.com/enterprise/3.5/rest/reference/repos#get-all-environments"
}`. We do not use environments and I am not sure if it is offered for the enterprise solution. 

## Possible Solution
Have the insights plugin be configurable so that you can choose not to show the environments card. 
Another option, handle the error differently. https://github.com/RoadieHQ/roadie-backstage-plugins/blob/4afa4fbde40102a06c13ad0d4a3f4a210521a6d3/plugins/frontend/backstage-plugin-github-insights/src/components/Widgets/EnvironmentsCard/EnvironmentsCard.tsx#L58 If the environments are not found show an error message only in the environments card not in the larger insights card.

## Context
Currently the plugin doesn't work for us. 

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.2.3
- `@backstage/integration` version: 1.4.1
- roadiehq/backstage-plugin-github-insights@2.3.2

**Comment by jef** [comment]
Also getting this, but we do use environments.

**Comment by kissmikijr** [comment]
@sarahpmedeiros  Thanks for reporting this, I agree it should handle it a lot more gracefully! Would you be up for fixing it? 

@jef Could you please open a separate issue if you do use and you should see the environments and we can tackle it in that one.

**Comment by sarahpmedeiros** [comment]
Absolutely!

**Comment by jef** [comment]
I figured out the issue. If the GitHub app doesn't have **Read** permissions on **Environments**, then it will fail to pull that information.

Sorry in advanced for commenting here too 😅 Could be worthwhile to add that note to the docs!

Thank you! 😌

**Comment by sarahpmedeiros** [comment]
@kissmikijr I was affected by the Wayfair Layoffs on Friday and I will not have the bandwidth (or access to GHE) to fix this bug right now. I'm sorry about that!

**Comment by kissmikijr** [comment]
@sarahpmedeiros Sorry to hear :( I hope you are doing ok, let me know if I could help you somehow!

**Comment by mtyranski** [comment]
@jef 

> I figured out the issue. If the GitHub app doesn't have **Read** permissions on **Environments**, then it will fail to pull that information.
>

What version of Github has the **Environments** permission?  I'm not seeing this in github documentation or in our local version of github.

**Comment by mtyranski** [comment]
NVM, I see it's only for Github Apps not Oauth

**Comment by errskipower** [comment]
Hi @kissmikijr - I can take this on!

**Comment by deeparavirdc** [comment]
Running into the same issue **without** explicitly loading `EnvironmentCard`. 
<img width="1526" alt="Screen Shot 2023-04-06 at 8 55 39 AM" src="https://user-images.githubusercontent.com/104038058/230433697-45d2b87b-fe21-499a-84fe-62dd4a8ac28d.png">
When loading `InsightsPage` it always loads the environment card - https://github.com/RoadieHQ/roadie-backstage-plugins/blob/689fb1806c7767a36b4ea49eef9d53c5e9b64193/plugins/frontend/backstage-plugin-github-insights/src/components/InsightsPage/InsightsPage.tsx#L54 which when doesn't render, errors out the whole page. 
Currently the plugin doesn't work.

**Comment by deeparavirdc** [comment]
Update on the above - In addition to what jef [mentioned](https://github.com/RoadieHQ/roadie-backstage-plugins/issues/817#issuecomment-1400780834), the github app must also have `actions:read` permission in order to combat `EnvironmentsCard` issue. So `environment:read` and `actions:read` for the backstage github app did it for me.

**Comment by jef** [comment]
great question @mtyranski; unfortunately we're using github enterprise (cloud).

**Comment by Vity01** [comment]
I can confirm this behavior. 
We use Github Enterprise with Actions *disabled*. Unfortunately the plugin relies on it while loading Environments card.
Calling Github fails with 404 even the access rights (actions:read) are properly set (curl returns 404 as well).
Please add an option to disable this feature or to add some kind of detection of disabled Github Actions.

**Comment by nanjingfm** [comment]
Maybe we need to ignore response codes like 404，Because both the license and readme files may not exist.
<img width="583" alt="image" src="https://user-images.githubusercontent.com/18688410/236374189-efe7d2da-01dd-4ce1-affb-744ffb041559.png">

**Comment by yanyuxuanz** [comment]
> 

Any further useful solutions about this?

**Comment by aj84276** [comment]
any solution on this please?

**Comment by adrien-saunier-decathlon** [comment]
@punkle I just made an attempt to fix the bug here :

https://github.com/RoadieHQ/roadie-backstage-plugins/issues/817

First contribution for me, I hope I followed the pratices 🙏
