### ISSUE TITLE
Github Login request when accessing Component PRs  / Issues

### ISSUE THREAD

**Issue by victorgrubio** [RoadieHQ/roadie-backstage-plugins#824]
I have created a Backstage instance that uses the https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-pull-requests plugin. I have setup Github Enterprise OAuth authentication successfully. I am trying to access a catalog entity (service)  and I get the login dialog for Github when the `<EntityGithubPullRequestsContent />` or `<EntityGithubPullRequestsOverviewCard />`are enabled on `packages/app/src/components/catalog/EntityPage.tsx`

## Expected Behavior

Access the entity without requesting the login again.

## Current Behavior

It requests Github login

<img width="1454" alt="Screenshot 2023-01-24 at 09 54 03" src="https://user-images.githubusercontent.com/45101838/214249966-7c51f7e7-6ce8-45e0-b4c4-4b98bef4800a.png">

## Steps to Reproduce

- Setup Github Enterprise Authentication on a backstage instance with a custom provider.
- Try to access a component while having the PR content available on the entity

Overview content as an example at `packages/app/src/components/catalog/EntityPage.tsx`
```
const overviewContent = (
  <Grid container spacing={3} alignItems="stretch">
    {entityWarningContent}
    <Grid item md={6}>
      <EntityAboutCard variant="gridItem" />
    </Grid>
    <Grid item md={6} xs={12}>
      <EntityCatalogGraphCard variant="gridItem" height={400} />
    </Grid>

    <Grid item md={4} xs={12}>
      <EntityLinksCard />
    </Grid>
    <Grid item md={8} xs={12}>
      <EntityHasSubcomponentsCard variant="gridItem" />
    </Grid>
    <Grid item md={6}>
        <EntityGithubPullRequestsOverviewCard />
      </Grid>
  </Grid>
);
```

## Context

Just in case, I'll paste my current provider since its customised due to org requirements:
`packages/backend/src/plugins/auth.ts`
```
function githubResolver(): AuthProviderFactory{
  return providers.github.create({
    signIn: {
      resolver: async (info, ctx) => {
        const {
          profile: {},
          result: {
            fullProfile: {
              username,
            }
          }
        } = info;
        if (username === undefined) {
          throw new Error();
        }
        return ctx.signInWithCatalogUser({
          filter: {
            kind: ['User'],
            'metadata.name': username
          },
        });
      },
    } 
  })
}

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  
  return await createRouter({
    ...env,
    providerFactories: {
      ...defaultAuthProviderFactories,
      github: githubResolver()
    },
  });
}
```

## Your Environment

│ ├── @backstage/app-defaults@1.1.0
│ ├── @backstage/catalog-model@1.1.5
│ ├── @backstage/cli@0.22.1 deduped
│ ├── @backstage/core-app-api@1.4.0
│ ├── @backstage/core-components@0.12.3
│ ├── @backstage/core-plugin-api@1.3.0
│ ├── @backstage/integration-react@1.1.9
│ ├── @backstage/plugin-api-docs@0.8.14
│ ├── @backstage/plugin-azure-devops@0.2.5
│ ├── @backstage/plugin-catalog-common@1.0.10
│ ├── @backstage/plugin-catalog-graph@0.2.26
│ ├── @backstage/plugin-catalog-import@0.9.4
│ ├── @backstage/plugin-catalog-react@1.2.4
│ ├── @backstage/plugin-catalog@1.7.2
│ ├── @backstage/plugin-github-actions@0.5.14
│ ├── @backstage/plugin-github-pull-requests-board@0.1.8
│ ├── @backstage/plugin-home@0.4.30
│ ├── @backstage/plugin-kubernetes@0.7.7
│ ├── @backstage/plugin-org@0.6.4
│ ├── @backstage/plugin-permission-react@0.4.9
│ ├── @backstage/plugin-scaffolder@1.10.1
│ ├── @backstage/plugin-search-react@1.4.0
│ ├── @backstage/plugin-search@1.0.7
│ ├── @backstage/plugin-stack-overflow@0.1.10
│ ├── @backstage/plugin-tech-radar@0.6.0
│ ├── @backstage/plugin-techdocs-module-addons-contrib@1.0.9
│ ├── @backstage/plugin-techdocs-react@1.1.2
│ ├── @backstage/plugin-techdocs@1.4.3
│ ├── @backstage/plugin-user-settings@0.6.2

│ ├── @roadiehq/backstage-plugin-github-pull-requests@2.3.0

Backend 
│ ├── @backstage/backend-common@0.18.1
│ ├── @backstage/backend-tasks@0.4.2
│ ├── @backstage/catalog-client@1.3.0
│ ├── @backstage/catalog-model@1.1.5 deduped
│ ├── @backstage/cli@0.22.1 deduped
│ ├── @backstage/config@1.0.6
│ ├── @backstage/plugin-app-backend@0.3.41
│ ├── @backstage/plugin-auth-backend@0.17.4
│ ├── @backstage/plugin-auth-node@0.2.10
│ ├── @backstage/plugin-azure-devops-backend@0.3.20
│ ├── @backstage/plugin-catalog-backend-module-github@0.2.4
│ ├── @backstage/plugin-catalog-backend@1.7.1
│ ├── @backstage/plugin-cost-insights@0.12.3
│ ├── @backstage/plugin-kubernetes-backend@0.9.2
│ ├── @backstage/plugin-permission-backend@0.5.16
│ ├── @backstage/plugin-permission-common@0.7.3
│ ├── @backstage/plugin-permission-node@0.7.4
│ ├── @backstage/plugin-proxy-backend@0.2.35
│ ├── @backstage/plugin-scaffolder-backend@1.10.1
│ ├── @backstage/plugin-search-backend-module-pg@0.5.2
│ ├── @backstage/plugin-search-backend-node@1.1.2
│ ├── @backstage/plugin-search-backend@1.2.2
│ ├── @backstage/plugin-stack-overflow-backend@0.1.10
│ ├── @backstage/plugin-techdocs-backend@1.5.2

**Comment by kissmikijr** [comment]
The mentioned plugins uses the active user's oauth credentials, not the globally configured github creds that you setup in the backend of your backstage. They are built this way because of the github API rate limits. With the current solution every user has its own set of rate limits tied to its oauth token instead of using the centralized one which would exhaust pretty quickly if every backstage user would use it. The drawback is that the users will need to authenticate to github to get the token. I hope it makes sense.

**Comment by victorgrubio** [comment]
I get that the plugin uses the oauth credentials from the active users. Therefore even though we set up the authentication to use the github oauth app, we have to re-auth in the specific tabs to get the information from the plugin?

That's a drawback in terms of usability, specially to get the insights. I can couple with having to re-login for pull requests tab. I hope there is an alternative in the future. Regards!
