### ISSUE TITLE
ArgoCD: open up `getBaseUrl` and `fetchDecode` methods in `ArgoCDApiClient`

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [RoadieHQ/roadie-backstage-plugins#836]
## Feature Suggestion
I am extending the argocd plugin in order to add a few more API calls to ArgoCD, `clusters` being the one I am focused right now. I am extending by extending the `ArgoCDApiClient` class. It seems my extension method would need to utilize the same logic as `getBaseUrl` and `fetchDecode`, 2 private methods. Right now, I would have to re implement that logic. 

## Possible Implementation
Making those 2 methods public would ease up extending the plugins with more functionality.

**Comment by karlhaworth** [comment]
@SayakMukhopadhyay I think @iain-b originally made `fetchDecode` private and I followed with making `getBaseUrl` private.

If you make a PR to change it, I wouldn't have a problem with it moving forward.

How can I help?

**Comment by SayakMukhopadhyay** [comment]
@karlhaworth sure, I have added a PR linked to this issue. Its a really simple one and should not break anything so it should be good to go in a patch release.
