### ISSUE TITLE
[jira-plugin] Add filter by label 

### ISSUE THREAD

**Issue by antoniomuso** [RoadieHQ/roadie-backstage-plugins#861]
Hi all, first, thanks for the excellent work you are doing. 

## Feature Suggestion

I think it can be helpful to have the possibility to add a filter by label ex. `jira/label`, as an alternative to the component annotation. 

## Context

Currently we don't use components in my organization, having this feature can be very useful.

**Comment by antoniomuso** [comment]
Hi @martina-if, I did the PR :-)

**Comment by martina-if** [comment]
Thank you @antoniomuso !! I'll tag someone from the team so they take a look!
