### ISSUE TITLE
I would like to be able to disable info logging on http-request action

### ISSUE THREAD

**Issue by Teemukoivumaa** [RoadieHQ/roadie-backstage-plugins#863]
## Feature Suggestion

Would like to be able to toggle info logging off, so it doesn't log user's credentials when they are included in request URL.

Line in question: [backstageRequest](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request/src/actions/run/backstageRequest.ts#L108)

## Possible Implementation
Keep the info logging on by default. But make it possible to turn it off. 

(Some fast text coding, can contribute legit code)
Could be as simple as this:

backstageRequest.ts
```typescript
infoLogging: {
  title: 'Turn info logging off',
  description: 'Option to turn info logging off',
  type: boolean,
  default: true
},
...
// default is true so only when infoLogging==false it skips
if (infoLogging == true){
    ctx.logger.info(
       `Creating ${method} request with ${this.id} scaffolder action against ${input.path}`,
    );
}
```

## Context

I would like to create a template that send's a request with some secret credentials in request url. Example http://www.example.com/userID=xxx&userAuth=xxx

**Comment by kissmikijr** [comment]
Hey, I think this addition makes sense, would you be up for creating a PR for it ?

**Comment by Teemukoivumaa** [comment]
Great to hear. I'll make a PR today

**Comment by Teemukoivumaa** [comment]
PR opened: https://github.com/RoadieHQ/roadie-backstage-plugins/pull/873

**Comment by Teemukoivumaa** [comment]
PR now closed, marking as done
