### ISSUE TITLE
Display more information in the ArgoCD plugin

### ISSUE THREAD

**Issue by christophe-f** [RoadieHQ/roadie-backstage-plugins#881]
## Feature Suggestion

We would like to submit a PR with the following changes:

1. Update to the ArgoCD History

Currently the ArgoCD plugin will show the following information:
- Name
- Deploy Started
- Deployed At
- Deploy Duration
- Revision

We would like to add the following additional information:
- Deployment status
- Better display of the deploy date/time
- Message
- Author

2. Update the Overview card
- Display the error message in case of an error
- Add a link to ArgoCD

3. Few bugs fixes

If you agree with the changes, we can start working on it right away.

**Comment by jorgelainfiesta** [comment]
Hi @christophe-f ! this sounds great, thank you!

**Comment by martina-if** [comment]
cc @karlhaworth

**Comment by karlhaworth** [comment]
@christophe-f awesome. appreciated

**Comment by yzhao583** [comment]
PR submitted: [https://github.com/RoadieHQ/roadie-backstage-plugins/pull/907](https://github.com/RoadieHQ/roadie-backstage-plugins/pull/907)
Reviews are appreciated!

**Comment by yzhao583** [comment]
The PR has been merged, this task is done.
