### ISSUE TITLE
Argo plugin throws 500 if single instance is down

### ISSUE THREAD

**Issue by Lucas-Desouza** [RoadieHQ/roadie-backstage-plugins#899]
## Expected Behavior

The plugin should be able to handle a single instance being down without completely breaking functionality.

## Current Behavior

If you have more than one instance and any one of them fails to respond, you'll see an error message saying `Error occurred while fetching data. TypeError: c.map is not a function...` 

## Steps to Reproduce

Setup the plugin with more than one instance and cause an outage in one of the instances.

## Possible Solution

Return data for all instances that respond properly

## Context

This creates a larger issue because instances that may be less stable like Nonprod instances can impact visibility of Prod instances. 

## Your Environment

- Backstage version: 1.11.1
- @roadiehq/backstage-plugin-argo-cd: 2.2.8

**Comment by martina-if** [comment]
Hi @Lucas-Desouza , that sounds like a bug indeed. We are focusing on other areas at the moment, would you be up for contributing a fix? We would be happy to review it and merge it.

**Comment by Lucas-Desouza** [comment]
My team plans on working on this soon when we get a chance.

**Comment by aharken** [comment]
Working on this issue

**Comment by planeiii-te** [comment]
Is this related to #1072?
