### ISSUE TITLE
`catalog-backend-module-okta` User/Group Entity Providers allow custom Entity Descriptor Callbacks

### ISSUE THREAD

**Issue by alecjacobs5401** [RoadieHQ/roadie-backstage-plugins#900]
It would be great to have full control over the emitted `UserEntity` and `GroupEntity` entities that are generated from the `OktaUserEntityProvider` and `OktaGroupEntityProvider` entity providers respectively.

This could be a fully backwards compatible and default to the currently generated `UserEntity` and `GroupEntity` definitions.

## Feature Suggestion

* `OktaUserEntityProvider` should provide a new optional argument on instantiation `entityFromOktaUser`
* `OktaGroupEntityProvider` should provide a new optional argument on instantiation `entityFromOktaGroup`

Doing so will allow for customization of emitted Entities for Backstage instances that have extensions to the default Catalog schema (e.g. custom relations). Additionally, it allows for just greater configuration of Entities based on the Okta Resources.

## Possible Implementation

For `OktaUserEntityProvider`, for example:

```diff
+import type { User as OktaUser } from '@okta/okta-sdk-nodejs';
+export type OktaUserEntityGenerator = (user: OktaUser, options: { annotations: Record<string, string> }) => Entity   // specifically Entity for custom extensions

export class OktaUserEntityProvider extends OktaEntityProvider {
  private readonly namingStrategy: UserNamingStrategy;
+ private readonly entityFromOktaUser: OktaUserEntityGenerator;
  private readonly userFilter?: string;
  private readonly orgUrl: string;

  static fromConfig(
    config: Config,
    options: {
      logger: winston.Logger;
      namingStrategy?: UserNamingStrategies | UserNamingStrategy;
+     entityFromOktaUser?: OktaUserEntityGenerator;
    },
  ) {
    const accountConfig = getAccountConfig(config);

    return new OktaUserEntityProvider(accountConfig, options);
  }

  constructor(
    accountConfig: AccountConfig,
    options: {
      logger: winston.Logger;
      namingStrategy?: UserNamingStrategies | UserNamingStrategy;
+     entityFromOktaUser?: OktaUserEntityGenerator;
    },
  ) {
    super([accountConfig], options);
    this.namingStrategy = userNamingStrategyFactory(options.namingStrategy);
    this.userFilter = accountConfig.userFilter;
    this.orgUrl = accountConfig.orgUrl;
+   this.entityFromOktaUser = options.entityFromOktaUser
  }

  async run(): Promise<void> {
    if (!this.connection) {
      throw new Error('Not initialized');
    }

    this.logger.info(`Providing user resources from okta: ${this.orgUrl}`);
    const userResources: UserEntity[] = [];

    const client = this.getClient(this.orgUrl, ['okta.users.read']);

    const defaultAnnotations = await this.buildDefaultAnnotations();

    const allUsers = await client.listUsers({ search: this.userFilter });

    await allUsers.each(user => {
      try {
-       const userEntity = userEntityFromOktaUser(user, this.namingStrategy, {
+       const userEntity: Entity = this.entityFromOktaUser?.(user, { annotations: defaultAnnotations }) || userEntityFromOktaUser(user, this.namingStrategy, {
          annotations: defaultAnnotations,
        });
        userResources.push(userEntity);
      } catch (e: unknown) {
        assertError(e);
        this.logger.warn(`failed to add user to group: ${e.message}`);
      }
    });

    await this.connection.applyMutation({
      type: 'full',
      entities: userResources.map(entity => ({
        entity,
        locationKey: this.getProviderName(),
      })),
    });
    this.logger.info(
      `Finished providing ${userResources.length} user resources from okta: ${this.orgUrl}`,
    );
  }
}
```

Similar implementation for the `OktaGroupEntityProvider`

## Context

Our Backstage instance has some custom schema extensions. We would love to use this package to start pulling in User entities from our Okta instance, but we would need to create our own User Entity Provider that inherits from the exported `OktaEntityProvider` to fully meet our usage criteria.

This seemed like a potentially good approach to contribute back if y'all would find it useful to give the implementing catalog the ability to fine tune generated Entities.

Happy to open up a Pull Request as well for this!

**Comment by alecjacobs5401** [comment]
>What would you like to add to the entities? 

Our Okta users have _a lot_ of custom field metadata attached to them that we would like to pull in (things like Job Descriptions, Hire Dates, employee IDs, etc.).

We also want to consume `status` and other non `profile` fields as annotations.

>Wouldn't it be possible to use a processor for it? We could add an annotation and the custom processor could act based on that.

Are you thinking you would throw the entire user entity from Okta as an annotation and then we could operate from there? Or are you thinking instead to take some allowlist of paths on the User that you would put as an annotation that can then be referenced later?

Really, one of our other use cases is to create _non_ User entities from Okta Users. We have a lot of Service Accounts in our Okta that we want to ingest as `Resource` entities that have specific team ownership and serve specific Components, for example. 

Being able to control exactly what _type_ of Entity is returned is also beneficial (hence my recommendation for `entityFromOktaUser` to return an `Entity` type)

**Comment by knksmith57** [comment]
If it's useful color, this overridable transform pattern is also the strategy folks settled on for the GithubOrgEntityProvider in core ([here's the `defaultUserTransformer()` for reference](https://github.com/backstage/backstage/blob/v1.12.1/plugins/catalog-backend-module-github/src/lib/defaultTransformers.ts#L56-L84))

If we wanted/needed to support anything beyond molding the Okta<>Backstage objects, I'd strong +1 to using a processor, but the problem with that approach is that it forces one of two bad options:
1. either the implementor (this library) has to shove the entire object somewhere else _anyway_ for the processor to act on
2. _or_ the adopter has to make a similar, duplicate call back to Okta to get the necessary data we just threw away in the provider

Or maybe there's a 3rd option that we haven't thought of yet?

Either way, supporting a transform function is an elegant, if imperfect, interface for offering a high level of flexibility and reuse of this package.

**Comment by kissmikijr** [comment]
Yea my initial idea was to just fetch again in a processor. I would not append the whole data as an annotation that's for sure. 

I think this makes sense would give the biggest flexibility, my only concerne is it might result in a worse default base user experience if all of the companies start to implement their own transformer. I think there will be things that would benefit everyone, but I think it's a potential small price to pay for it.

**Comment by regicsolutions** [comment]
> Yea my initial idea was to just fetch again in a processor. I would not append the whole data as an annotation that's for sure. 
> 
> 
> 
> I think this makes sense would give the biggest flexibility, my only concerne is it might result in a worse default base user experience if all of the companies start to implement their own transformer. I think there will be things that would benefit everyone, but I think it's a potential small price to pay for it.

I was also hoping for the same level of control and enable my own transformer to push additional custom annotations for both User and Group entities pulled in from Okta. If building a custom `defaultOktaOrgProcessor` is the recommended path, would it be possible to add a sample processor for reference to the documentation?

**Comment by kissmikijr** [comment]
>  If building a custom defaultOktaOrgProcessor is the recommended path, would it be possible to add a sample processor for reference to the documentation?

I think at this point I'd say it is *not* the recommended way. This issue is the new recommendation however I do not know when we will be able to implement this. Contributions are appreciated, would you like to take a stab at it @regicsolutions ?

**Comment by regicsolutions** [comment]
> >  If building a custom defaultOktaOrgProcessor is the recommended path, would it be possible to add a sample processor for reference to the documentation?
> 
> 
> 
> I think at this point I'd say it is *not* the recommended way. This issue is the new recommendation however I do not know when we will be able to implement this. Contributions are appreciated, would you like to take a stab at it @regicsolutions ?

Is the recommendation to use the same approach as the ldap provider? https://backstage.io/docs/integrations/ldap/org/#customize-the-provider

**Comment by kissmikijr** [comment]
Yea basically

**Comment by alecjacobs5401** [comment]
Catching back up on this thread - @kissmikijr are you open to contributions for my suggested feature of having a `defaultUserTransformer` here that can be overwritten by a provided transformer function?

My concern around implementing a processor to do _another_ fetch request based on the current emitted user is hitting Rate limits upstream against Okta. It might not be _too_ bad ([1000/minute for fetching individual user](https://developer.okta.com/docs/reference/rl-global-mgmt/), but we have quite a lot of users we're currently pulling in

**Comment by sabinasiddiqi** [comment]
Bump on this thread ^

**Comment by ianaktr** [comment]
Hello! 👋  It looks like all agreed to have `defaultUserTransformer` and the option to overwrite it by the provided transformer function. Is that right? Does it mean that you are open to this contribution? 

We would also benefit from this feature. We don't have a lot of custom annotations but we do have some. For example, we want to have filled `description` and `picture` in the user entity. Would be cool to have it working here instead of forking the entire plugin.
