### ISSUE TITLE
Security Insights: Dependabot Table / Page doesn't handle fixed alerts

### ISSUE THREAD

**Issue by dotboris** [RoadieHQ/roadie-backstage-plugins#934]
In the GitHub security insights plugin, the table that shows the list of dependabot alerts doesn't seem to consider any alerts that are fixed. It treats them all as if they're open.

## Expected Behavior

When an alert has been fixed, it should show up as having the fixed status and not appear when filtering with the open status. I also expect to be able to filter by the fixed status.

## Current Behavior

Fixed alerts are shown as if they're open.

## Steps to Reproduce

1. In a repository with Dependabot alerts configured, fix a vulnerability or just find a vulnerability that you already fixed
2. Go in Backstage and look at the Dependabot tab for the associated component.
3. Look for your fixed vulnerability
4. Notice that it's labelled as "Open"

## Possible Solution

Looking at the implementation, it seems like the table uses `repository.vulnerabilityAlerts.nodes[*].dismissedAt` to distinguish between the Open and Dismissed state. Turns out that there's a `state` field that could be used. See: https://docs.github.com/en/graphql/reference/objects#repositoryvulnerabilityalert

I believe that using state here would simplify some of the logic in the table as well.

## Context

In my case, I have a custom tab that shows both the dependabot summary widget and the table at the same time. There's a pretty obvious disconnect because the widget shows 0 alerts but the table shows a bunch of them.

Here's a screenshot to help illustrate the issue

![image](https://user-images.githubusercontent.com/1874242/230478871-b125ce81-2d6e-4984-b8e3-83df4711e742.png)

For reference, here's what in GitHub's security tab:

![image](https://user-images.githubusercontent.com/1874242/230479266-3884a458-206a-48a1-9ecc-92dd1f44a05a.png)

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.4.0
- `@backstage/integration` version: 1.4.3

**Comment by martina-if** [comment]
Hi @dotboris , I'm not the most familiar with this plugin but it does seem indeed like a bug. Would you be willing to provide a pull request to fix this? It would be highly appreciated! cc @kissmikijr

**Comment by dotboris** [comment]
@martina-if I think that I can provide a pull request. I can't make promises but I'm pretty sure that getting this fixed will fall within my upcoming sprint.

**Comment by martina-if** [comment]
Thank you!

**Comment by dotboris** [comment]
PR is ready: #941

**Comment by dotboris** [comment]
PR has been merged and released. Tested on my end and it works great. Closing. Thank you everyone.
