### ISSUE TITLE
Support for Multipart request in RequestBody

### ISSUE THREAD

**Issue by Ipuvi** [RoadieHQ/roadie-backstage-plugins#937]
## Feature Suggestion

Hi Team

I have 2 requests regarding the backstage HTTP request action.
1. Can we support form data in the request body?
2. Can we provide user option to pass the path params along with query params for http request?

Can someone please help with why this support is not in current action?

## Possible Implementation

I have done changes in my local for the same, if it's not some restrictions from product requirements, I can raise a pull request.

## Context

I'm trying to automate bitbucket webhook creation in my service template project using `backstage-http-action` but it doesn't support form-data/multipart request, thus instead of creating a complete custom action would want to extend `backstage-http-action` to support the same.

**Comment by kissmikijr** [comment]
@Ipuvi Sorry for being quite late on this. I don't know any product requirements why we didn't implement it. Would you be up to creating a PR for them? I suggest doing it in two separate PRs.
