### ISSUE TITLE
`catalog-backend-module-okta` fix documentation on possibly undefined config

### ISSUE THREAD

**Issue by tillepille** [RoadieHQ/roadie-backstage-plugins#944]
## Expected Behavior

When following the documentation from: https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/backend/catalog-backend-module-okta#example-configuration-1

the build should succeed afterwards.

## Current Behavior

```bash
#18 0.282 $ tsc
#18 5.633 packages/backend/src/plugins/catalog.ts:16:58 - error TS2532: Object is possibly 'undefined'.
#18 5.633 
#18 5.633 16   const userProvider = OktaUserEntityProvider.fromConfig(oktaConfig[0], {
#18 5.633                                                             ~~~~~~~~~~
#18 5.633 
#18 5.633 
#18 5.633 Found 1 error in packages/backend/src/plugins/catalog.ts:16
#18 5.633 
```

## Steps to Reproduce

Use the code from documentation above and try to build backstage.

## Possible Solution

I replaced the okta config with

```js
  const oktaConfig = env.config.getOptionalConfigArray('catalog.providers.okta') || [];
```

That does work, but feels a little hacky.
## Context

Trying to import Okta users into Backstage

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.4.0
- `@backstage/integration` version: 1.4.3

**Comment by kissmikijr** [comment]
Thanks for reporting this. Would you be up for fixing the documentation?

**Comment by tillepille** [comment]
@kissmikijr Hope that does the job! 🙃
