### ISSUE TITLE
Review Requests Github Signin results in No Auth Provider

### ISSUE THREAD

**Issue by devinvenable** [RoadieHQ/roadie-backstage-plugins#956]
After installing software, following blog post guidance, still unable to authenticate via Demo Review Requests component.

## Expected Behavior

Prompted to login to Github then continue.

## Current Behavior

No Auth Provider error.

## Steps to Reproduce

1. Installed https://github.com/RoadieHQ/roadie-backstage-plugins
2. Accessing Review Requests in demo page results in pop-up with Exception: No Auth Provider
3. Followed steps here: https://roadie.io/blog/github-auth-backstage/

Note that I have these env variables set when I run "yarn dev"

GITHUB_TOKEN
AUTH_GITHUB_CLIENT_ID
AUTH_GITHUB_CLIENT_SECRET

Also, I am authenticating with person token, not Github apps.

## Context

I wish to demo roadie capabilities next week to some colleages.

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.4.0
- `@backstage/integration` version: 1.4.3

**Comment by kissmikijr** [comment]
What's your app-config.yaml's `auth` and `integrations` section look like (without revealing exact secret values!)

**Comment by kissmikijr** [comment]
@devinvenable is this issue still happening for you?
