### ISSUE TITLE
[backstage-plugin-github-pull-requests] return hours to `Average Time Of PR Until Merge` display

### ISSUE THREAD

**Issue by sploschee** [RoadieHQ/roadie-backstage-plugins#959]
## Feature Suggestion

extend the new `Average Time Of PR Until Merge` display provided in [PR-922](https://github.com/RoadieHQ/roadie-backstage-plugins/pull/922/files) to include hours.

## Possible Implementation

Apologies, I haven't tested this suggestion.
```
const avgTimeUntilMerge = Duration.fromMillis(avgTimeUntilMergeDiff)
      .shiftTo('months', 'days', 'hours')
```

## Context

Would it be possible to extend the `Average Time Of PR Until Merge` display to include hours.
The new updated output provides `Average Time Of PR Until Merge` in months and days.  
<img width="627" alt="image" src="https://user-images.githubusercontent.com/19555355/234788537-2233ff2c-aecc-424f-a526-73fa456cb6c4.png">

Our engineers had a better UX with hours
<img width="642" alt="image" src="https://user-images.githubusercontent.com/19555355/234788723-efc2d0b4-61e2-4428-966d-65ae654650dc.png">

**Comment by sploschee** [comment]
I would be happy with  "0 months, 0 days, 11 hours" over  "0 months, 0.46 days" tbh.

**Comment by punkle** [comment]
@sploschee I think you have convinced me.. :D would you like to have a go at creating a pull request?

**Comment by sploschee** [comment]
Resolved via https://github.com/RoadieHQ/roadie-backstage-plugins/pull/966

**Comment by punkle** [comment]
@sploschee well done, that was totally appreciated! Thanks again.
