### ISSUE TITLE
React-dom error on backstage-plugin-github-pull-requests after upgrading to Backstage v1.13.2

### ISSUE THREAD

**Issue by arriiiella** [RoadieHQ/roadie-backstage-plugins#976]
After upgrading to Backstage v1.13.2,  we are having issues with the pull request plugin and are seeing `react-dom` errors.

## Expected Behavior

When opening the github pull request tab in Backstage, the plugin will render and be accessible for use.

## Current Behavior

When opening the github pull request tab in Backstage, the plugin throws an error and is unable to be used.

## Steps to Reproduce

1. Follow the [backstage upgrade helper](https://backstage.github.io/upgrade-helper/?from=1.12.0&to=1.13.2) for upgrading to v1.13.2
2. Install `@roadiehq/backstage-plugin-github-pull-requests` version `^2.5.10`
3. Follow steps [here](https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-pull-requests) to add plugin to Backstage instance
4. Launch Backstage app and navigate to a service in the catalog
5. Open the pull request tab

## Possible Solution

It looks like the most recent [Backstage upgrade](https://github.com/backstage/backstage/pull/17116) adds a new package to the `app/package.json` which we think is causing this issue.
```    
    "react-router": "^6.3.0",
```
Removing this package fixes the issue for us. 
But we are not keen on going against Backstage's recommendations and wanted to see if the plugin had a fix for this.
We have already upgraded the plugin to the latest version.

## Context
![image](https://user-images.githubusercontent.com/68117668/236415928-fef38ff8-b435-4035-bd14-6a85f211a8b8.png)

![image](https://user-images.githubusercontent.com/68117668/236414734-d61c2562-e0a0-4308-9189-7fc48e8ad035.png)

## Your Environment

- `@backstage/plugin-catalog-react` version: ^1.5.0
- `@backstage/integration` version: NA 
-  `react-dom` version: ^17.0.2
- `react-router-dom` version : ^6.3.0
- `@roadiehq/backstage-plugin-github-pull-requests` version:  "^2.5.10",

**Comment by arriiiella** [comment]
Thanks. If there's any other information I can provide please let me know

**Comment by alecjacobs5401** [comment]
We're getting the same thing but from the `buildkite` plugin as well

**Comment by alecjacobs5401** [comment]
Managed to find a workaround by manually deleting old cached versions of `react-router*` in `yarn.lock` and regenerating, basically needed a reset to get on the right versions of `react-router-dom` it seems
