### ISSUE TITLE
http:backstage:request incorrectly decode url path

### ISSUE THREAD

**Issue by sergeyshevch** [RoadieHQ/roadie-backstage-plugins#995]
## Expected Behavior

http:backstage:request action provides incorrect paths encoding. Looks like underlying backstage API changed.

## Current Behavior

Url incorrectly encoded what lead to 404 erorrs.

## Steps to Reproduce

I have template with `http:backstage:request` action with input:
`path: '/proxy/simple/content-api/cdn/reset'`

in app-config I have

```
proxy:
  '/simple/content-api':
    target: 'mydomain'
    changeOrigin: true
```

As result I get requests to `/api/proxy%2Fsimple%2Fcontent-api%2Fcdn%2Freset` instead of `/api/proxy/simple/content-api/cdn/reset`

All worked correctly before backstage 1.14.0 upgrade 

## Possible Solution

Looks like backstage itself using
```
this.discoveryApi.getBaseUrl('proxy')}/<your-proxy-uri>
```
https://github.com/backstage/backstage/blob/master/docs/tutorials/using-backstage-proxy-within-plugin.md?plain=1#L128

## Your Environment

```
"@backstage/backend-common": "^0.18.5",
"@backstage/backend-tasks": "^0.5.2",
"@backstage/catalog-client": "^1.4.1",
"@backstage/catalog-model": "^1.3.0",
"@backstage/config": "^1.0.7",
"@roadiehq/scaffolder-backend-module-http-request": "^4.0.6",
```

**Comment by sergeyshevch** [comment]
If someone is looking for a workaround. Vendor locally this package and replace generateBackstageUrl func with 

```
export const generateBackstageUrl = (
  discovery: DiscoveryApi,
  path: string,
): Promise<string> => {
  let requestPath = path.startsWith('/') ? path.substring(1) : path;
  requestPath = requestPath.replace('proxy/', '');

  return discovery.getBaseUrl('proxy').then(url => {
    return `${url}/${requestPath}`;
  });
};
```

Quite ugly but works

**Comment by punkle** [comment]
@sergeyshevch would you be able to produce a pull request with same?

**Comment by sergeyshevch** [comment]
Ok. I will create PR today

**Comment by Nitinvonage** [comment]
I am facing this issue even with backstage 1.13 as well, do we have any other workaround for time being

**Comment by sergeyshevch** [comment]
Not yet. I switched to other urgent tasks now. Feel free to create PR

**Comment by bisongeeOVO** [comment]
I've created a PR for this so far on: https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1003
